/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import Json.JsonInformation;
import java.awt.Font;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;


public class Adapter extends javax.swing.JFrame {

    int mouseX, mouseY;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    JsonInformation info;
    int pj=0;
    Font myFont2 = new Font("Wingdings", Font.PLAIN, 18);
    Fonts typeFont = new Fonts();
    
    public Adapter() throws IOException, FileNotFoundException, ParseException {
        this.info = new JsonInformation("src/Assets/IMG/Adapter/questions.json");
        initComponents();
        npcSelector();
        
        lblTittle.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblTittle1.setFont(typeFont.fontV(typeFont.instruments, 1, 14));
        lblTittle2.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblTittle3.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblReset.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblYes.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblNo.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkDefault_Img.png");
        setImageLabel(lblMinish,"src/Assets/IMG/Adapter/minish_Icon.png");
        setImageLabel(lblDeku,"src/Assets/IMG/Adapter/deku_Icon.png");
        setImageLabel(lblGoron,"src/Assets/IMG/Adapter/goron_Icon.png");
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    

    
    
    private void npcSelector(){
        int NPC =(int)(Math.random() * 3) + 1;
        this.pj=NPC;
        switch (NPC){
            case 1:
                setImageLabel(lblcharacter1,"src/Assets/IMG/Adapter/npcMinish_Img.png");
                lblQuestion.setText("<html>"+info.getData("minish")+"<html>");
                lblTittle1.setText("<html>Kleir (El Bardo Minish)<html>");
                
            break;
            
            case 2:
                setImageLabel(lblcharacter1,"src/Assets/IMG/Adapter/npcDeku_Img.png");
                lblQuestion.setText("<html>"+info.getData("deku")+"<html>");
                lblTittle1.setText("<html>Frontasio (El Rey Deku)<html>");
                
            break;
           
            case 3:
                setImageLabel(lblcharacter1,"src/Assets/IMG/Adapter/npcGoron_Img.png");
                lblQuestion.setText("<html>"+info.getData("goron")+"<html>");
                lblTittle1.setText("<html>Paco (El Herrero Goron)<html>");
                
            break;
        
        }
        
        
        
        
        
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        btnMinish = new javax.swing.JPanel();
        lblMinish = new javax.swing.JLabel();
        btnDeku = new javax.swing.JPanel();
        lblDeku = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        lblReset = new javax.swing.JLabel();
        btnGoron = new javax.swing.JPanel();
        lblGoron = new javax.swing.JLabel();
        lblcharacter1 = new javax.swing.JLabel();
        lblcharacter = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        btnYes = new javax.swing.JPanel();
        lblYes = new javax.swing.JLabel();
        btnNo = new javax.swing.JPanel();
        lblNo = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblTittle1 = new javax.swing.JLabel();
        lblTittle2 = new javax.swing.JLabel();
        lblTittle3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        btnMinish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinishMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinishLayout = new javax.swing.GroupLayout(btnMinish);
        btnMinish.setLayout(btnMinishLayout);
        btnMinishLayout.setHorizontalGroup(
            btnMinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMinish, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnMinishLayout.setVerticalGroup(
            btnMinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMinish, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        btnDeku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDeku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDekuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDekuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDekuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDekuLayout = new javax.swing.GroupLayout(btnDeku);
        btnDeku.setLayout(btnDekuLayout);
        btnDekuLayout.setHorizontalGroup(
            btnDekuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDeku, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnDekuLayout.setVerticalGroup(
            btnDekuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDeku, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnDeku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("Reset");
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 70, 30));

        btnGoron.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGoron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoronMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoronMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoronMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGoronLayout = new javax.swing.GroupLayout(btnGoron);
        btnGoron.setLayout(btnGoronLayout);
        btnGoronLayout.setHorizontalGroup(
            btnGoronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGoron, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnGoronLayout.setVerticalGroup(
            btnGoronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGoron, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGoron, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lblcharacter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcharacter1.setText("jLabel1");
        jPanel1.add(lblcharacter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 150, 260));

        lblcharacter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblcharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, 260));

        lblQuestion.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        lblQuestion.setText("jLabel3");
        jPanel1.add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 300, 150));

        btnYes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYes.setText("Si");
        lblYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblYesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblYesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnYesLayout = new javax.swing.GroupLayout(btnYes);
        btnYes.setLayout(btnYesLayout);
        btnYesLayout.setHorizontalGroup(
            btnYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblYes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnYesLayout.setVerticalGroup(
            btnYesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblYes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 50, 50));

        btnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo.setText("No");
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNoLayout = new javax.swing.GroupLayout(btnNo);
        btnNo.setLayout(btnNoLayout);
        btnNoLayout.setHorizontalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnNoLayout.setVerticalGroup(
            btnNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 50, 50));

        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Goron");
        jPanel1.add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, -1));

        lblTittle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle1.setText("jLabel1");
        jPanel1.add(lblTittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 86, 150, 30));

        lblTittle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle2.setText("Minish");
        jPanel1.add(lblTittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, -1));

        lblTittle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle3.setText("Deku");
        jPanel1.add(lblTittle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblMinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinishMouseEntered
        btnMinish.setOpaque(true);
        btnMinish.setBackground(colorEntered);
    }//GEN-LAST:event_lblMinishMouseEntered

    private void lblMinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinishMouseExited
        btnMinish.setOpaque(true);
        btnMinish.setBackground(colorDefault);
    }//GEN-LAST:event_lblMinishMouseExited

    private void lblDekuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDekuMouseEntered
        btnDeku.setOpaque(true);
        btnDeku.setBackground(colorEntered);
    }//GEN-LAST:event_lblDekuMouseEntered

    private void lblDekuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDekuMouseExited
        btnDeku.setOpaque(true);
        btnDeku.setBackground(colorDefault);
    }//GEN-LAST:event_lblDekuMouseExited

    private void lblGoronMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoronMouseEntered
        btnGoron.setOpaque(true);
        btnGoron.setBackground(colorEntered);
    }//GEN-LAST:event_lblGoronMouseEntered

    private void lblGoronMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoronMouseExited
        btnGoron.setOpaque(true);
        btnGoron.setBackground(colorDefault);
    }//GEN-LAST:event_lblGoronMouseExited

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        btnReset.setOpaque(true);
        btnReset.setBackground(colorEntered);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        btnReset.setOpaque(true);
        btnReset.setBackground(colorDefault);
    }//GEN-LAST:event_lblResetMouseExited

    private void lblMinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinishMouseClicked
        setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkMinish_Img.png");
        if(pj==1){
            lblQuestion.setFont(typeFont.fontV(typeFont.instruments, 0, 18));
        }else{
            lblQuestion.setFont(myFont2);
        }
        
    }//GEN-LAST:event_lblMinishMouseClicked

    private void lblDekuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDekuMouseClicked
        setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkDeku_Img.png");
        if(pj==2){
            lblQuestion.setFont(typeFont.fontV(typeFont.instruments, 0, 18));
        }else{
            lblQuestion.setFont(myFont2);
        }
        
    }//GEN-LAST:event_lblDekuMouseClicked

    private void lblGoronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoronMouseClicked
        setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkGoron_Img.png");
        if(pj==3){
            lblQuestion.setFont(typeFont.fontV(typeFont.instruments, 0, 18));
        }else{
            lblQuestion.setFont(myFont2);
        }
        
    }//GEN-LAST:event_lblGoronMouseClicked

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkDefault_Img.png");
        lblQuestion.setFont(myFont2);
        
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblYesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYesMouseEntered
        btnYes.setOpaque(true);
        btnYes.setBackground(colorEntered);
    }//GEN-LAST:event_lblYesMouseEntered

    private void lblYesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYesMouseExited
        btnYes.setOpaque(true);
        btnYes.setBackground(colorDefault);
    }//GEN-LAST:event_lblYesMouseExited

    private void lblNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseEntered
        btnNo.setOpaque(true);
        btnNo.setBackground(colorEntered);
    }//GEN-LAST:event_lblNoMouseEntered

    private void lblNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseExited
        btnNo.setOpaque(true);
        btnNo.setBackground(colorDefault);
    }//GEN-LAST:event_lblNoMouseExited

    private void lblYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYesMouseClicked
        String validacion = lblQuestion.getFont().toString();
        if(validacion.contains("Wingdings")){
           JOptionPane.showMessageDialog(null, "Para responder debes traducir primero la pregunta, no todo es a lo random");
        } else {
            
            
            if(pj==1){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                } 
            }
            
            if(pj==2){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                } 
            }
            
            if(pj==3){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                } 
            }
            
            
            npcSelector();
            lblQuestion.setFont(myFont2);
            setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkDefault_Img.png");
        }
        
        
        
        
    }//GEN-LAST:event_lblYesMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        String validacion = lblQuestion.getFont().toString();
    
        if(validacion.contains("Wingdings")){
           JOptionPane.showMessageDialog(null, "Para responder debes traducir primero la pregunta, no todo es a lo random");
        } else {
            
            
            if(pj==1){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                } 
            }
            
            if(pj==2){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera incorrecta"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                } 
            }
            
            if(pj==3){
                if(info.returnNumber()==0){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                }
                
                if(info.returnNumber()==1){
                   JOptionPane.showMessageDialog(null, "Contestaste de manera correcta!!!"); 
                } 
            }
            
            
            npcSelector();
            lblQuestion.setFont(myFont2);
            setImageLabel(lblcharacter,"src/Assets/IMG/Adapter/linkDefault_Img.png");
        }
    }//GEN-LAST:event_lblNoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adapter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adapter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adapter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adapter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Adapter().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Adapter.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Adapter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnDeku;
    private javax.swing.JPanel btnGoron;
    private javax.swing.JPanel btnMinish;
    private javax.swing.JPanel btnNo;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnYes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeku;
    private javax.swing.JLabel lblGoron;
    private javax.swing.JLabel lblMinish;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JLabel lblTittle2;
    private javax.swing.JLabel lblTittle3;
    private javax.swing.JLabel lblYes;
    private javax.swing.JLabel lblcharacter;
    private javax.swing.JLabel lblcharacter1;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
