/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Bridge extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    int damage=0, durability=0, fdura=0;
    String item="";
    
    
    public Bridge() {
        initComponents();
        decorator();
        setImageLabel(lblSword,"src/Assets/IMG/Bridge/sword_Img.png");
        setImageLabel(lblShield,"src/Assets/IMG/Bridge/shield_Img.png");
        setImageLabel(lblStaff,"src/Assets/IMG/Bridge/staff_Img.png");
        setImageLabel(lblChange,"src/Assets/IMG/Bridge/change_Icon.png");
        setImageLabel(lblLink,"src/Assets/IMG/Bridge/Link_Img.png");
        
        
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        lblSubtittle.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblSubtittle1.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblSubtittle2.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblDamage.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblDurability.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lbltextDamage.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lbltextDurability.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblGive.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblUse.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblRepair.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblBuff.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblText.setFont(typeFont.fontV(typeFont.instruments, 0, 13));
        lblTittle.setFont(typeFont.fontV(typeFont.instruments, 1, 14));
        lblTittle1.setFont(typeFont.fontV(typeFont.instruments, 1, 14));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        pnlSeparator2 = new javax.swing.JPanel();
        btnSword = new javax.swing.JPanel();
        lblSword = new javax.swing.JLabel();
        btnShield = new javax.swing.JPanel();
        lblShield = new javax.swing.JLabel();
        btnStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        txtDamage = new javax.swing.JTextField();
        txtDurability = new javax.swing.JTextField();
        btnGive = new javax.swing.JPanel();
        lblGive = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        lblItem1 = new javax.swing.JLabel();
        lblSubtittle = new javax.swing.JLabel();
        lblDurability = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        btnChange = new javax.swing.JPanel();
        lblChange = new javax.swing.JLabel();
        lbltextDurability = new javax.swing.JLabel();
        btnUse = new javax.swing.JPanel();
        lblUse = new javax.swing.JLabel();
        btnRepair = new javax.swing.JPanel();
        lblRepair = new javax.swing.JLabel();
        btnBuff = new javax.swing.JPanel();
        lblBuff = new javax.swing.JLabel();
        lblSubtittle1 = new javax.swing.JLabel();
        lblSubtittle2 = new javax.swing.JLabel();
        lblDamage = new javax.swing.JLabel();
        lbltextDamage = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblTittle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 50, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 59, 2, 380));

        btnSword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSwordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSwordLayout = new javax.swing.GroupLayout(btnSword);
        btnSword.setLayout(btnSwordLayout);
        btnSwordLayout.setHorizontalGroup(
            btnSwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSword, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnSwordLayout.setVerticalGroup(
            btnSwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSword, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnSword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        btnShield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblShield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShieldMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnShieldLayout = new javax.swing.GroupLayout(btnShield);
        btnShield.setLayout(btnShieldLayout);
        btnShieldLayout.setHorizontalGroup(
            btnShieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShield, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnShieldLayout.setVerticalGroup(
            btnShieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShield, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnShield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, 40));

        btnStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStaffMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnStaffLayout = new javax.swing.GroupLayout(btnStaff);
        btnStaff.setLayout(btnStaffLayout);
        btnStaffLayout.setHorizontalGroup(
            btnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btnStaffLayout.setVerticalGroup(
            btnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 40, 40));
        jPanel1.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 180, 180));

        txtDamage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDamageKeyTyped(evt);
            }
        });
        jPanel1.add(txtDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 80, -1));

        txtDurability.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDurabilityKeyTyped(evt);
            }
        });
        jPanel1.add(txtDurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 80, -1));

        btnGive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGive.setText("Dar Item a Link");
        lblGive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGiveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGiveMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGiveLayout = new javax.swing.GroupLayout(btnGive);
        btnGive.setLayout(btnGiveLayout);
        btnGiveLayout.setHorizontalGroup(
            btnGiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGive, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnGiveLayout.setVerticalGroup(
            btnGiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGive, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnGive, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 40));

        lblLink.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        lblLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLink.setText("link");
        jPanel1.add(lblLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 180, 190));
        jPanel1.add(lblItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 90, 90));

        lblSubtittle.setText("Stats Item:");
        jPanel1.add(lblSubtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 140, -1));

        lblDurability.setText("000");
        jPanel1.add(lblDurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 70, -1));
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 340, 50));

        btnChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblChange.setText("jLabel1");
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblChangeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnChangeLayout = new javax.swing.GroupLayout(btnChange);
        btnChange.setLayout(btnChangeLayout);
        btnChangeLayout.setHorizontalGroup(
            btnChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChangeLayout.createSequentialGroup()
                .addComponent(lblChange)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        btnChangeLayout.setVerticalGroup(
            btnChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChange, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 40, 40));

        lbltextDurability.setText("Durabilidad");
        jPanel1.add(lbltextDurability, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 70, -1));

        btnUse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUse.setText("Usar Item");
        lblUse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUseLayout = new javax.swing.GroupLayout(btnUse);
        btnUse.setLayout(btnUseLayout);
        btnUseLayout.setHorizontalGroup(
            btnUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUse, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnUseLayout.setVerticalGroup(
            btnUseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUse, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 100, 30));

        btnRepair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblRepair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepair.setText("Reparar Item");
        lblRepair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRepairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRepairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRepairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRepairLayout = new javax.swing.GroupLayout(btnRepair);
        btnRepair.setLayout(btnRepairLayout);
        btnRepairLayout.setHorizontalGroup(
            btnRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRepair, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnRepairLayout.setVerticalGroup(
            btnRepairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRepair, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 100, 30));

        btnBuff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBuff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuff.setText("Mejorar Item");
        lblBuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuffMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuffLayout = new javax.swing.GroupLayout(btnBuff);
        btnBuff.setLayout(btnBuffLayout);
        btnBuffLayout.setHorizontalGroup(
            btnBuffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuff, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBuffLayout.setVerticalGroup(
            btnBuffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuff, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 100, 30));

        lblSubtittle1.setText("Durabilidad:");
        jPanel1.add(lblSubtittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, -1));

        lblSubtittle2.setText("Daño:");
        jPanel1.add(lblSubtittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 80, -1));

        lblDamage.setText("000");
        jPanel1.add(lblDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 60, -1));

        lbltextDamage.setText("Daño");
        jPanel1.add(lbltextDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 70, -1));

        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Interfaz de personaje");
        jPanel1.add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 160, -1));

        lblTittle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle1.setText("Interfaz de Item");
        jPanel1.add(lblTittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblSwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSwordMouseEntered
        btnSword.setOpaque(true);
        btnSword.setBackground(colorEntered);        
    }//GEN-LAST:event_lblSwordMouseEntered

    private void lblSwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSwordMouseExited
        btnSword.setOpaque(true);
        btnSword.setBackground(colorDefault); 
    }//GEN-LAST:event_lblSwordMouseExited

    private void lblShieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShieldMouseEntered
        btnShield.setOpaque(true);
        btnShield.setBackground(colorEntered);    
    }//GEN-LAST:event_lblShieldMouseEntered

    private void lblShieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShieldMouseExited
        btnShield.setOpaque(true);
        btnShield.setBackground(colorDefault);    
    }//GEN-LAST:event_lblShieldMouseExited

    private void lblStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMouseEntered
        btnStaff.setOpaque(true);
        btnStaff.setBackground(colorEntered);
    }//GEN-LAST:event_lblStaffMouseEntered

    private void lblStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMouseExited
        btnStaff.setOpaque(true);
        btnStaff.setBackground(colorDefault);   
    }//GEN-LAST:event_lblStaffMouseExited

    private void lblGiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiveMouseEntered
        btnGive.setOpaque(true);
        btnGive.setBackground(colorEntered);
    }//GEN-LAST:event_lblGiveMouseEntered

    private void lblGiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiveMouseExited
        btnGive.setOpaque(true);
        btnGive.setBackground(colorDefault);  
    }//GEN-LAST:event_lblGiveMouseExited

    private void lblChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseEntered
        btnChange.setOpaque(true);
        btnChange.setBackground(colorEntered);
    }//GEN-LAST:event_lblChangeMouseEntered

    private void lblChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseExited
        btnChange.setOpaque(true);
        btnChange.setBackground(colorDefault);
    }//GEN-LAST:event_lblChangeMouseExited

    private void lblUseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUseMouseEntered
        btnUse.setOpaque(true);
        btnUse.setBackground(colorEntered);
    }//GEN-LAST:event_lblUseMouseEntered

    private void lblUseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUseMouseExited
        btnUse.setOpaque(true);
        btnUse.setBackground(colorDefault);
    }//GEN-LAST:event_lblUseMouseExited

    private void lblRepairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseEntered
        btnRepair.setOpaque(true);
        btnRepair.setBackground(colorEntered);
    }//GEN-LAST:event_lblRepairMouseEntered

    private void lblRepairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseExited
        btnRepair.setOpaque(true);
        btnRepair.setBackground(colorDefault);
    }//GEN-LAST:event_lblRepairMouseExited

    private void lblBuffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuffMouseEntered
        btnBuff.setOpaque(true);
        btnBuff.setBackground(colorEntered);
    }//GEN-LAST:event_lblBuffMouseEntered

    private void lblBuffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuffMouseExited
        btnBuff.setOpaque(true);
        btnBuff.setBackground(colorDefault);
    }//GEN-LAST:event_lblBuffMouseExited

    private void lblSwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSwordMouseClicked
        setImageLabel(lblItem,"src/Assets/IMG/Bridge/sword_Img.png");
        item="sword";
    }//GEN-LAST:event_lblSwordMouseClicked

    private void lblShieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShieldMouseClicked
        setImageLabel(lblItem,"src/Assets/IMG/Bridge/shield_Img.png");
        item="shield";
    }//GEN-LAST:event_lblShieldMouseClicked

    private void lblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStaffMouseClicked
        setImageLabel(lblItem,"src/Assets/IMG/Bridge/staff_Img.png");
        item="staff";
    }//GEN-LAST:event_lblStaffMouseClicked

    private void lblChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseClicked
     
        if(lblLink.getText().equals("link")){
            setImageLabel(lblLink,"src/Assets/IMG/Bridge/DekuLink_Img.png");
            lblLink.setText("dekuLink");
        }else if(lblLink.getText().equals("dekuLink")){
            setImageLabel(lblLink,"src/Assets/IMG/Bridge/Link_Img.png");
            lblLink.setText("link");
        }

        
        
    }//GEN-LAST:event_lblChangeMouseClicked

    private void txtDamageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDamageKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (txtDamage.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDamageKeyTyped

    private void txtDurabilityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDurabilityKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (txtDurability.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDurabilityKeyTyped

    private void lblGiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiveMouseClicked
        if(!item.isBlank()){      
            if(txtDurability.getText().isEmpty() && txtDamage.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tu item tiene que tener durabilidad y daño");
            }else{
                setImageLabel(lblItem1,"src/Assets/IMG/Bridge/"+item+"_Img.png");
                lblDamage.setText(txtDamage.getText());
                lblDurability.setText(txtDurability.getText());
                this.damage= Integer.parseInt(txtDamage.getText());
                this.durability = Integer.parseInt(txtDurability.getText());
                this.fdura = Integer.parseInt(txtDurability.getText());
            }
            
        }else{
           JOptionPane.showMessageDialog(null, "No seleccionaste un item"); 
        }

        
    }//GEN-LAST:event_lblGiveMouseClicked

    private void lblUseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUseMouseClicked
        if(!item.isBlank()){
            if(durability>0){
                switch (item){
                    case "sword":
                        lblText.setText("<html>"+lblLink.getText()+" arremete con su espada para atacar a los enemigos<html>");
                        this.durability=this.durability-10;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                    case "shield":
                        lblText.setText("<html>"+lblLink.getText()+" usa con astucia su escudo para defenderse de los enemigos<html>");
                        this.durability=this.durability-10;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                    case "staff":
                        lblText.setText("<html>"+lblLink.getText()+" conjura las magias de las arenas con su baculo para atacar a los enemigos<html>");
                        this.durability=this.durability-20;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                }
            }else{
                JOptionPane.showMessageDialog(null, "La durabilidad esta en 0, no lo puedes usar mas!!, debes repararlo"); 
            }
        }else{
            JOptionPane.showMessageDialog(null, lblLink.getText()+" no tiene un item"); 
        }
    }//GEN-LAST:event_lblUseMouseClicked

    private void lblRepairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairMouseClicked
        if(!item.isBlank()){
            if(this.durability<(fdura+1)){

                switch (item){
                    case "sword":
                        lblText.setText("<html>"+lblLink.getText()+" utiliza sus conocimienntos para reparar su espada<html>");
                        this.durability=this.durability+5;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                    case "shield":
                        lblText.setText("<html>"+lblLink.getText()+" pule su escudo y lo repara para seguir luchando<html>");
                        this.durability=this.durability+5;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                    case "staff":
                        lblText.setText("<html>"+lblLink.getText()+" golpea su palo contra un arbol para repararlo<html>");
                        this.durability=this.durability+5;
                        if(this.durability<0){
                            this.durability=0;  
                        }
                        lblDurability.setText(String.valueOf(this.durability));
                    break;

                }
            }else{
                JOptionPane.showMessageDialog(null, "Tu item no puede repararse mas!!"); 
            }
        }else{
            JOptionPane.showMessageDialog(null, lblLink.getText()+" no tiene un item"); 
        }
        
    }//GEN-LAST:event_lblRepairMouseClicked

    private void lblBuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuffMouseClicked
        if(!item.isBlank()){
            if(lblLink.getText().equals("dekuLink")){

                lblText.setText("Deku-Link potencia sus items y los lleva a otro nivel");
                this.durability=this.durability+999;
                this.damage=this.damage+999;

                lblDurability.setText(String.valueOf(this.durability));
                lblDamage.setText(String.valueOf(this.damage));

            }else{
                JOptionPane.showMessageDialog(null, "No estas en modo Deku-Link"); 
            }
        }else{
            JOptionPane.showMessageDialog(null, lblLink.getText()+" no tiene un item");
        }
        
    }//GEN-LAST:event_lblBuffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bridge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnBuff;
    private javax.swing.JPanel btnChange;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnGive;
    private javax.swing.JPanel btnRepair;
    private javax.swing.JPanel btnShield;
    private javax.swing.JPanel btnStaff;
    private javax.swing.JPanel btnSword;
    private javax.swing.JPanel btnUse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuff;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblDurability;
    private javax.swing.JLabel lblGive;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItem1;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblRepair;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblSubtittle;
    private javax.swing.JLabel lblSubtittle1;
    private javax.swing.JLabel lblSubtittle2;
    private javax.swing.JLabel lblSword;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JLabel lblUse;
    private javax.swing.JLabel lbltextDamage;
    private javax.swing.JLabel lbltextDurability;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JLabel txtCerrar;
    private javax.swing.JTextField txtDamage;
    private javax.swing.JTextField txtDurability;
    // End of variables declaration//GEN-END:variables
}
