/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Composite extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorSelected=new Color(128, 128, 129);
    Color colorDefault=new Color(214, 217, 223);
    String valueT="", valueR="", valueE="";
    
    public Composite() {
        initComponents();
        decorator();
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        
        //Setear imagenes base
        setImageLabel(lblbMap,"src/Assets/IMG/composite/map_Icon.png");
        setImageLabel(lblTree,"src/Assets/IMG/composite/tree_Icon.png");
        setImageLabel(lblRock,"src/Assets/IMG/composite/rock_Icon.png");
        setImageLabel(lblEnemy,"src/Assets/IMG/composite/enemy_Icon.png");
        setImageLabel(lblReset,"src/Assets/IMG/composite/change_Icon.png");
    }
    
    private void setImg(String tree, String rock, String enemy ,JLabel space){
        String path=tree+rock+enemy;
        setImageLabel(space,"src/Assets/IMG/composite/combinations/"+path+".png");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubtittle4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        pnlSeparator2 = new javax.swing.JPanel();
        btnMap = new javax.swing.JPanel();
        lblbMap = new javax.swing.JLabel();
        btnTree = new javax.swing.JPanel();
        lblTree = new javax.swing.JLabel();
        btnRock = new javax.swing.JPanel();
        lblRock = new javax.swing.JLabel();
        btnEnemy = new javax.swing.JPanel();
        lblEnemy = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        lblReset = new javax.swing.JLabel();
        btnSpace1 = new javax.swing.JPanel();
        lblSpace1 = new javax.swing.JLabel();
        btnSpace2 = new javax.swing.JPanel();
        lblSpace2 = new javax.swing.JLabel();
        btnSpace3 = new javax.swing.JPanel();
        lblSpace3 = new javax.swing.JLabel();
        btnSpace4 = new javax.swing.JPanel();
        lblSpace4 = new javax.swing.JLabel();
        btnSpace5 = new javax.swing.JPanel();
        lblSpace5 = new javax.swing.JLabel();
        btnSpace6 = new javax.swing.JPanel();
        lblSpace6 = new javax.swing.JLabel();
        btnSpace7 = new javax.swing.JPanel();
        lblSpace7 = new javax.swing.JLabel();
        btnSpace8 = new javax.swing.JPanel();
        lblSpace8 = new javax.swing.JLabel();
        btnSpace9 = new javax.swing.JPanel();
        lblSpace9 = new javax.swing.JLabel();
        btnSpace10 = new javax.swing.JPanel();
        lblSpace10 = new javax.swing.JLabel();
        lblMap = new javax.swing.JLabel();
        lblSubtittle = new javax.swing.JLabel();
        lblSubtittle1 = new javax.swing.JLabel();
        lblSubtittle2 = new javax.swing.JLabel();
        lblSubtittle3 = new javax.swing.JLabel();
        lblSubtittle5 = new javax.swing.JLabel();

        lblSubtittle4.setText("Mapa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 59, 2, 380));

        btnMap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblbMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbMapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbMapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbMapMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMapLayout = new javax.swing.GroupLayout(btnMap);
        btnMap.setLayout(btnMapLayout);
        btnMapLayout.setHorizontalGroup(
            btnMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbMap, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnMapLayout.setVerticalGroup(
            btnMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbMap, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        btnTree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTreeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTreeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTreeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTreeLayout = new javax.swing.GroupLayout(btnTree);
        btnTree.setLayout(btnTreeLayout);
        btnTreeLayout.setHorizontalGroup(
            btnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTree, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnTreeLayout.setVerticalGroup(
            btnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTree, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        btnRock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblRock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRockMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRockLayout = new javax.swing.GroupLayout(btnRock);
        btnRock.setLayout(btnRockLayout);
        btnRockLayout.setHorizontalGroup(
            btnRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRock, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnRockLayout.setVerticalGroup(
            btnRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRock, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        btnEnemy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblEnemy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnemyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnemyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnemyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEnemyLayout = new javax.swing.GroupLayout(btnEnemy);
        btnEnemy.setLayout(btnEnemyLayout);
        btnEnemyLayout.setHorizontalGroup(
            btnEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnEnemyLayout.setVerticalGroup(
            btnEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 50, 50));

        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        btnSpace1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace1Layout = new javax.swing.GroupLayout(btnSpace1);
        btnSpace1.setLayout(btnSpace1Layout);
        btnSpace1Layout.setHorizontalGroup(
            btnSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace1Layout.setVerticalGroup(
            btnSpace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 60));

        btnSpace2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace2Layout = new javax.swing.GroupLayout(btnSpace2);
        btnSpace2.setLayout(btnSpace2Layout);
        btnSpace2Layout.setHorizontalGroup(
            btnSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace2Layout.setVerticalGroup(
            btnSpace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, 60));

        btnSpace3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace3Layout = new javax.swing.GroupLayout(btnSpace3);
        btnSpace3.setLayout(btnSpace3Layout);
        btnSpace3Layout.setHorizontalGroup(
            btnSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace3Layout.setVerticalGroup(
            btnSpace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 60, 60));

        btnSpace4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace4Layout = new javax.swing.GroupLayout(btnSpace4);
        btnSpace4.setLayout(btnSpace4Layout);
        btnSpace4Layout.setHorizontalGroup(
            btnSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace4Layout.setVerticalGroup(
            btnSpace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, 60));

        btnSpace5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace5Layout = new javax.swing.GroupLayout(btnSpace5);
        btnSpace5.setLayout(btnSpace5Layout);
        btnSpace5Layout.setHorizontalGroup(
            btnSpace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace5Layout.setVerticalGroup(
            btnSpace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, 60));

        btnSpace6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace6Layout = new javax.swing.GroupLayout(btnSpace6);
        btnSpace6.setLayout(btnSpace6Layout);
        btnSpace6Layout.setHorizontalGroup(
            btnSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace6Layout.setVerticalGroup(
            btnSpace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 60, 60));

        btnSpace7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace7Layout = new javax.swing.GroupLayout(btnSpace7);
        btnSpace7.setLayout(btnSpace7Layout);
        btnSpace7Layout.setHorizontalGroup(
            btnSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace7Layout.setVerticalGroup(
            btnSpace7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 60, 60));

        btnSpace8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace8Layout = new javax.swing.GroupLayout(btnSpace8);
        btnSpace8.setLayout(btnSpace8Layout);
        btnSpace8Layout.setHorizontalGroup(
            btnSpace8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace8Layout.setVerticalGroup(
            btnSpace8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 60, 60));

        btnSpace9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace9Layout = new javax.swing.GroupLayout(btnSpace9);
        btnSpace9.setLayout(btnSpace9Layout);
        btnSpace9Layout.setHorizontalGroup(
            btnSpace9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace9Layout.setVerticalGroup(
            btnSpace9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 60, 60));

        btnSpace10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpace10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpace10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSpace10Layout = new javax.swing.GroupLayout(btnSpace10);
        btnSpace10.setLayout(btnSpace10Layout);
        btnSpace10Layout.setHorizontalGroup(
            btnSpace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnSpace10Layout.setVerticalGroup(
            btnSpace10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpace10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpace10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 60, 60));

        lblMap.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jPanel1.add(lblMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 570, 360));

        lblSubtittle.setText("Reset");
        jPanel1.add(lblSubtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 60, -1));

        lblSubtittle1.setText("Mapa");
        jPanel1.add(lblSubtittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 60, -1));

        lblSubtittle2.setText("Arbol");
        jPanel1.add(lblSubtittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 60, -1));

        lblSubtittle3.setText("Roca");
        jPanel1.add(lblSubtittle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 60, -1));

        lblSubtittle5.setText("Enemigo");
        jPanel1.add(lblSubtittle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblbMapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbMapMouseEntered
        btnMap.setOpaque(true);
        btnMap.setBackground(colorEntered);
    }//GEN-LAST:event_lblbMapMouseEntered

    private void lblbMapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbMapMouseExited
        btnMap.setOpaque(true);
        btnMap.setBackground(colorDefault);
    }//GEN-LAST:event_lblbMapMouseExited

    private void lblTreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTreeMouseEntered
        if (btnTree.getBackground().equals(colorDefault)) {
            btnTree.setOpaque(true);
            btnTree.setBackground(colorEntered);
        }
    }//GEN-LAST:event_lblTreeMouseEntered

    private void lblTreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTreeMouseExited
        if(btnTree.getBackground().equals(colorEntered)){
            btnTree.setOpaque(true);
            btnTree.setBackground(colorDefault);
        }
    }//GEN-LAST:event_lblTreeMouseExited

    private void lblRockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRockMouseEntered
        if (btnRock.getBackground().equals(colorDefault)) {
            btnRock.setOpaque(true);
            btnRock.setBackground(colorEntered);
        }
    }//GEN-LAST:event_lblRockMouseEntered

    private void lblRockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRockMouseExited
        if(btnRock.getBackground().equals(colorEntered)){
            btnRock.setOpaque(true);
            btnRock.setBackground(colorDefault);
        }
    }//GEN-LAST:event_lblRockMouseExited

    private void lblEnemyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnemyMouseEntered
        if (btnEnemy.getBackground().equals(colorDefault)) {
            btnEnemy.setOpaque(true);
            btnEnemy.setBackground(colorEntered);
        }
    }//GEN-LAST:event_lblEnemyMouseEntered

    private void lblEnemyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnemyMouseExited
        if(btnEnemy.getBackground().equals(colorEntered)){
            btnEnemy.setOpaque(true);
            btnEnemy.setBackground(colorDefault);
        }
    }//GEN-LAST:event_lblEnemyMouseExited

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        btnReset.setOpaque(true);
        btnReset.setBackground(colorEntered);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        btnReset.setOpaque(true);
        btnReset.setBackground(colorDefault);
    }//GEN-LAST:event_lblResetMouseExited

    private void lblbMapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbMapMouseClicked
       setImageLabel(lblMap,"src/Assets/IMG/composite/map_Img.png");
    }//GEN-LAST:event_lblbMapMouseClicked

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        lblMap.setIcon(null);
        lblSpace1.setIcon(null);
        lblSpace2.setIcon(null);
        lblSpace3.setIcon(null);
        lblSpace4.setIcon(null);
        lblSpace5.setIcon(null);
        lblSpace6.setIcon(null);
        lblSpace7.setIcon(null);
        lblSpace8.setIcon(null);
        lblSpace9.setIcon(null);
        lblSpace10.setIcon(null);
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTreeMouseClicked
                        
        if(evt.getButton()==1){
          btnTree.setBackground(colorSelected);
          this.valueT="t";
           
        }else{
          btnTree.setBackground(colorDefault);
          this.valueT="";
        }

    }//GEN-LAST:event_lblTreeMouseClicked

    private void lblRockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRockMouseClicked
        if(evt.getButton()==1){
          btnRock.setBackground(colorSelected);
          this.valueR="r";
           
        }else{
          btnRock.setBackground(colorDefault);
          this.valueR="";
        }
        
    }//GEN-LAST:event_lblRockMouseClicked

    private void lblEnemyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnemyMouseClicked
        if(evt.getButton()==1){
          btnEnemy.setBackground(colorSelected);
          this.valueE="e";
           
        }else{
          btnEnemy.setBackground(colorDefault);
          this.valueE="";
        }
    }//GEN-LAST:event_lblEnemyMouseClicked

    private void lblSpace1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace1MouseClicked

        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace1);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace1.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace1MouseClicked

    private void lblSpace2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace2MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace2);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace2.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace2MouseClicked

    private void lblSpace3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace3MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace3);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace3.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace3MouseClicked

    private void lblSpace4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace4MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace4);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace4.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace4MouseClicked

    private void lblSpace5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace5MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace5);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace5.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace5MouseClicked

    private void lblSpace6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace6MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace6);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace6.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace6MouseClicked

    private void lblSpace7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace7MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace7);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace7.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace7MouseClicked

    private void lblSpace8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace8MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace8);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace8.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace8MouseClicked

    private void lblSpace9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace9MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace9);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace9.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace9MouseClicked

    private void lblSpace10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpace10MouseClicked
        if(evt.getButton()==1){
            if(lblMap.getIcon()!=null){
                setImg(valueT, valueR, valueE, lblSpace10);
            }else{
                JOptionPane.showMessageDialog(null, "No puedes poner obstaculos, aun no has generado el mapa!!!");
            }
        }else{
          lblSpace10.setIcon(null);
        }
    }//GEN-LAST:event_lblSpace10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Composite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Composite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Composite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Composite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Composite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnEnemy;
    private javax.swing.JPanel btnMap;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnRock;
    private javax.swing.JPanel btnSpace1;
    private javax.swing.JPanel btnSpace10;
    private javax.swing.JPanel btnSpace2;
    private javax.swing.JPanel btnSpace3;
    private javax.swing.JPanel btnSpace4;
    private javax.swing.JPanel btnSpace5;
    private javax.swing.JPanel btnSpace6;
    private javax.swing.JPanel btnSpace7;
    private javax.swing.JPanel btnSpace8;
    private javax.swing.JPanel btnSpace9;
    private javax.swing.JPanel btnTree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblMap;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblRock;
    private javax.swing.JLabel lblSpace1;
    private javax.swing.JLabel lblSpace10;
    private javax.swing.JLabel lblSpace2;
    private javax.swing.JLabel lblSpace3;
    private javax.swing.JLabel lblSpace4;
    private javax.swing.JLabel lblSpace5;
    private javax.swing.JLabel lblSpace6;
    private javax.swing.JLabel lblSpace7;
    private javax.swing.JLabel lblSpace8;
    private javax.swing.JLabel lblSpace9;
    private javax.swing.JLabel lblSubtittle;
    private javax.swing.JLabel lblSubtittle1;
    private javax.swing.JLabel lblSubtittle2;
    private javax.swing.JLabel lblSubtittle3;
    private javax.swing.JLabel lblSubtittle4;
    private javax.swing.JLabel lblSubtittle5;
    private javax.swing.JLabel lblTree;
    private javax.swing.JLabel lblbMap;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
