/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Flyweight extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    int contE1=0, contE2=0, ram1, ram2;
    
    public Flyweight() {
        initComponents();
        decorator();

    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        setImageLabel(lblEnemy,"src/Assets/IMG/Flyweight/noEnemy_Img.png");
        setImageLabel(lblEnemy1,"src/Assets/IMG/Flyweight/noEnemy_Img.png");
        lblTittle.setFont(typeFont.fontV(typeFont.instruments, 1, 18));
        lblTittle2.setFont(typeFont.fontV(typeFont.instruments, 1, 18));
        
        lblLife.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblDef.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblAtk.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblContE1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblContE2.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        
        lblRam.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblLife1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblDef1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblAtk1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblContE3.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblContE4.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblRam1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        
        lblBtnEnemy1.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblBtnEnemy2.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        lblReset.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        pnlSeparator2 = new javax.swing.JPanel();
        btnEnemy1 = new javax.swing.JPanel();
        lblBtnEnemy1 = new javax.swing.JLabel();
        btnEnemy2 = new javax.swing.JPanel();
        lblBtnEnemy2 = new javax.swing.JLabel();
        pnlSeparator3 = new javax.swing.JPanel();
        btnReset = new javax.swing.JPanel();
        lblReset = new javax.swing.JLabel();
        lblTittle2 = new javax.swing.JLabel();
        lblEgg = new javax.swing.JLabel();
        lblEnemy = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblContE1 = new javax.swing.JLabel();
        lblContE2 = new javax.swing.JLabel();
        lblRam = new javax.swing.JLabel();
        lblAtk = new javax.swing.JLabel();
        lblLife = new javax.swing.JLabel();
        lblDef = new javax.swing.JLabel();
        lblContE3 = new javax.swing.JLabel();
        lblLife1 = new javax.swing.JLabel();
        lblContE4 = new javax.swing.JLabel();
        lblRam1 = new javax.swing.JLabel();
        lblEnemy1 = new javax.swing.JLabel();
        lblAtk1 = new javax.swing.JLabel();
        lblEgg1 = new javax.swing.JLabel();
        lblDef1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 59, 2, 380));

        btnEnemy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBtnEnemy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnEnemy1.setText("Enemigo 1");
        lblBtnEnemy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnEnemy1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnEnemy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnEnemy1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEnemy1Layout = new javax.swing.GroupLayout(btnEnemy1);
        btnEnemy1.setLayout(btnEnemy1Layout);
        btnEnemy1Layout.setHorizontalGroup(
            btnEnemy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBtnEnemy1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnEnemy1Layout.setVerticalGroup(
            btnEnemy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBtnEnemy1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnEnemy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, 40));

        btnEnemy2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBtnEnemy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnEnemy2.setText("Enemigo 2");
        lblBtnEnemy2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnEnemy2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnEnemy2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnEnemy2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEnemy2Layout = new javax.swing.GroupLayout(btnEnemy2);
        btnEnemy2.setLayout(btnEnemy2Layout);
        btnEnemy2Layout.setHorizontalGroup(
            btnEnemy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBtnEnemy2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnEnemy2Layout.setVerticalGroup(
            btnEnemy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBtnEnemy2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnEnemy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        pnlSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator3Layout = new javax.swing.GroupLayout(pnlSeparator3);
        pnlSeparator3.setLayout(pnlSeparator3Layout);
        pnlSeparator3Layout.setHorizontalGroup(
            pnlSeparator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator3Layout.setVerticalGroup(
            pnlSeparator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 59, 2, 380));

        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("Reset");
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        lblTittle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle2.setText("Sin Flyweight");
        jPanel1.add(lblTittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, -1));
        jPanel1.add(lblEgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, 80));

        lblEnemy.setText("jLabel3");
        jPanel1.add(lblEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 210));

        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle.setText("Con Flyweight");
        jPanel1.add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        lblContE1.setText("ContadorE1:");
        jPanel1.add(lblContE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));

        lblContE2.setText("ContadorE2:");
        jPanel1.add(lblContE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, -1));

        lblRam.setText("Ram: ??? kb");
        jPanel1.add(lblRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 110, -1));

        lblAtk.setText("Ataque: ???");
        jPanel1.add(lblAtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 100, -1));

        lblLife.setText("Vida: ???");
        jPanel1.add(lblLife, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, -1));

        lblDef.setText("Defensa: ???");
        jPanel1.add(lblDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 100, -1));

        lblContE3.setText("Contador E1: ");
        jPanel1.add(lblContE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 110, -1));

        lblLife1.setText("Vida: ???");
        jPanel1.add(lblLife1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 100, -1));

        lblContE4.setText("Contador E2: ");
        jPanel1.add(lblContE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 110, -1));

        lblRam1.setText("Ram: ??? kb");
        jPanel1.add(lblRam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 110, -1));

        lblEnemy1.setText("jLabel3");
        jPanel1.add(lblEnemy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 160, 210));

        lblAtk1.setText("Ataque: ???");
        jPanel1.add(lblAtk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 100, -1));
        jPanel1.add(lblEgg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 90, 80));

        lblDef1.setText("Defensa: ???");
        jPanel1.add(lblDef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblBtnEnemy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy1MouseClicked
        setImageLabel(lblEnemy,"src/Assets/IMG/Flyweight/enemy1_Img.png");
        setImageLabel(lblEnemy1,"src/Assets/IMG/Flyweight/enemy1_Img.png");
        
        lblLife.setText("Vida: 200");
        lblDef.setText("Defensa: 50");
        lblAtk.setText("Ataque: 50");
        lblLife1.setText("Vida: 200");
        lblDef1.setText("Defensa: 50");
        lblAtk1.setText("Ataque: 50");
        
        contE1++; 
        lblContE1.setText("ContadorE1: "+contE1);
        lblContE3.setText("ContadorE1: "+contE1);
        

        
        if(contE1==1){
            ram1+=5;
            ram2+=5;
            
        }else{
            ram1+=2;
            ram2+=5;
        }
        
        lblRam.setText("Ram: "+ram1+" kb");
        lblRam1.setText("Ram: "+ram2+" kb");
        
        if(ram1>=1000){
          setImageLabel(lblEgg,"src/Assets/IMG/Flyweight/garbanzo_Img.jpeg");  
        }
        
        if(ram2>=1000){
          setImageLabel(lblEgg1,"src/Assets/IMG/Flyweight/garbanzo_Img.jpeg");    
        }
        
    }//GEN-LAST:event_lblBtnEnemy1MouseClicked

    private void lblBtnEnemy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy1MouseEntered
        btnEnemy1.setOpaque(true);
        btnEnemy1.setBackground(colorEntered);
    }//GEN-LAST:event_lblBtnEnemy1MouseEntered

    private void lblBtnEnemy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy1MouseExited
        btnEnemy1.setOpaque(true);
        btnEnemy1.setBackground(colorDefault);
    }//GEN-LAST:event_lblBtnEnemy1MouseExited

    private void lblBtnEnemy2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy2MouseClicked
        setImageLabel(lblEnemy,"src/Assets/IMG/Flyweight/enemy2_Img.png");
        setImageLabel(lblEnemy1,"src/Assets/IMG/Flyweight/enemy2_Img.png");

        
        lblLife.setText("Vida: 300");
        lblDef.setText("Defensa: 100");
        lblAtk.setText("Ataque: 20");
        lblLife1.setText("Vida: 300");
        lblDef1.setText("Defensa: 100");
        lblAtk1.setText("Ataque: 20");
        
        contE2++; 
        lblContE2.setText("ContadorE2: "+contE2);
        lblContE4.setText("ContadorE2: "+contE2);
        

        
        if(contE2==1){
            ram1+=6;
            ram2+=6;
        }else{
            ram1+=3;
            ram2+=6;
        }
        
        lblRam.setText("Ram: "+ram1+" kb");
        lblRam1.setText("Ram: "+ram2+" kb");
        
        if(ram1>=1000){
          setImageLabel(lblEgg,"src/Assets/IMG/Flyweight/garbanzo_Img.jpeg");  
        }
        
        if(ram2>=1000){
          setImageLabel(lblEgg1,"src/Assets/IMG/Flyweight/garbanzo_Img.jpeg");    
        }
    }//GEN-LAST:event_lblBtnEnemy2MouseClicked

    private void lblBtnEnemy2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy2MouseEntered
        btnEnemy2.setOpaque(true);
        btnEnemy2.setBackground(colorEntered);
    }//GEN-LAST:event_lblBtnEnemy2MouseEntered

    private void lblBtnEnemy2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnEnemy2MouseExited
        btnEnemy2.setOpaque(true);
        btnEnemy2.setBackground(colorDefault);
    }//GEN-LAST:event_lblBtnEnemy2MouseExited

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        setImageLabel(lblEnemy,"src/Assets/IMG/Flyweight/noEnemy_Img.png");
        setImageLabel(lblEnemy1,"src/Assets/IMG/Flyweight/noEnemy_Img.png");   
        lblEgg.setIcon(null);
        lblEgg1.setIcon(null);
        
        contE1=0;
        contE2=0;
        ram1=0;
        ram2=0;
        
        lblLife.setText("Vida: ???");
        lblDef.setText("Defensa: ???");
        lblAtk.setText("Ataque: ???");
        lblLife1.setText("Vida: ???");
        lblDef1.setText("Defensa: ???");
        lblAtk1.setText("Ataque: ???");  
        
        lblRam.setText("Ram: ??? kb");
        lblRam1.setText("Ram: ??? kb");
        
        lblContE1.setText("ContadorE2: ");
        lblContE2.setText("ContadorE2: ");
        lblContE3.setText("ContadorE2: ");
        lblContE4.setText("ContadorE2: ");
        
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        btnReset.setOpaque(true);
        btnReset.setBackground(colorEntered);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        btnReset.setOpaque(true);
        btnReset.setBackground(colorDefault);
    }//GEN-LAST:event_lblResetMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flyweight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flyweight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flyweight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flyweight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flyweight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnEnemy1;
    private javax.swing.JPanel btnEnemy2;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtk;
    private javax.swing.JLabel lblAtk1;
    private javax.swing.JLabel lblBtnEnemy1;
    private javax.swing.JLabel lblBtnEnemy2;
    private javax.swing.JLabel lblContE1;
    private javax.swing.JLabel lblContE2;
    private javax.swing.JLabel lblContE3;
    private javax.swing.JLabel lblContE4;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblDef1;
    private javax.swing.JLabel lblEgg;
    private javax.swing.JLabel lblEgg1;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblEnemy1;
    private javax.swing.JLabel lblLife;
    private javax.swing.JLabel lblLife1;
    private javax.swing.JLabel lblRam;
    private javax.swing.JLabel lblRam1;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTittle2;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JPanel pnlSeparator3;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
