/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;

public class Home extends javax.swing.JFrame {
    int mouseX,mouseY;
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        bgDecoration1 = new javax.swing.JPanel();
        LblTittle = new javax.swing.JLabel();
        LblDefinition = new javax.swing.JLabel();
        LblSubtittle1 = new javax.swing.JLabel();
        LblSubtittle2 = new javax.swing.JLabel();
        LblSubtittle3 = new javax.swing.JLabel();
        btnGlossary = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnObserver = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnStrategy = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnTemplateM = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnVisitor = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnState = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        btnChainOR = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnCommand = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnIterator = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnMediator = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMemento = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnProxy = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnFlyweight = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnFacade = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnDecorator = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnComposite = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnBridge = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnAdapter = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnSingleton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPrototype = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBuilder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAbstractF = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnFactoryM = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 3));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 840, 48));

        bgDecoration1.setBackground(new java.awt.Color(253, 196, 196));

        LblTittle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        LblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTittle.setText("Patrones de Diseño");

        javax.swing.GroupLayout bgDecoration1Layout = new javax.swing.GroupLayout(bgDecoration1);
        bgDecoration1.setLayout(bgDecoration1Layout);
        bgDecoration1Layout.setHorizontalGroup(
            bgDecoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDecoration1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(LblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        bgDecoration1Layout.setVerticalGroup(
            bgDecoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDecoration1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(LblTittle)
                .addContainerGap())
        );

        jPanel1.add(bgDecoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 51, 442, 60));

        LblDefinition.setFont(new java.awt.Font("Instrument Sans", 0, 17)); // NOI18N
        LblDefinition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDefinition.setText("<html>Los patrones de diseño son enfoques estándar para resolver problemas comunes en el desarrollo de software. Funcionan como esquemas o guías que pueden adaptarse a las necesidades específicas de un proyecto, ayudando a abordar situaciones recurrentes en el diseño del código. A diferencia de funciones o bibliotecas predefinidas, no se pueden copiar directamente en el programa. En su lugar, un patrón es una idea general que se implementa de acuerdo con las características y requisitos particulares del sistema en desarrollo, ofreciendo una solución flexible y ajustable al problema en cuestión.<html>");
        jPanel1.add(LblDefinition, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 800, 146));

        LblSubtittle1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblSubtittle1.setText("Comportamentales");
        jPanel1.add(LblSubtittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        LblSubtittle2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblSubtittle2.setText("Creacionales");
        jPanel1.add(LblSubtittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        LblSubtittle3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblSubtittle3.setText("Estructurales");
        jPanel1.add(LblSubtittle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        btnGlossary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons/Home/Glossary_Icon.png"))); // NOI18N
        jLabel23.setText("Glosario");

        javax.swing.GroupLayout btnGlossaryLayout = new javax.swing.GroupLayout(btnGlossary);
        btnGlossary.setLayout(btnGlossaryLayout);
        btnGlossaryLayout.setHorizontalGroup(
            btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );
        btnGlossaryLayout.setVerticalGroup(
            btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jPanel1.add(btnGlossary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 141, 50));

        btnObserver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Observer");

        javax.swing.GroupLayout btnObserverLayout = new javax.swing.GroupLayout(btnObserver);
        btnObserver.setLayout(btnObserverLayout);
        btnObserverLayout.setHorizontalGroup(
            btnObserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnObserverLayout.setVerticalGroup(
            btnObserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnObserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 141, 50));

        btnStrategy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Strategy");

        javax.swing.GroupLayout btnStrategyLayout = new javax.swing.GroupLayout(btnStrategy);
        btnStrategy.setLayout(btnStrategyLayout);
        btnStrategyLayout.setHorizontalGroup(
            btnStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStrategyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnStrategyLayout.setVerticalGroup(
            btnStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnStrategy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 141, 50));

        btnTemplateM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Template Method");

        javax.swing.GroupLayout btnTemplateMLayout = new javax.swing.GroupLayout(btnTemplateM);
        btnTemplateM.setLayout(btnTemplateMLayout);
        btnTemplateMLayout.setHorizontalGroup(
            btnTemplateMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnTemplateMLayout.setVerticalGroup(
            btnTemplateMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnTemplateM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 141, 50));

        btnVisitor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Visitor");

        javax.swing.GroupLayout btnVisitorLayout = new javax.swing.GroupLayout(btnVisitor);
        btnVisitor.setLayout(btnVisitorLayout);
        btnVisitorLayout.setHorizontalGroup(
            btnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisitorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnVisitorLayout.setVerticalGroup(
            btnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 141, 50));

        btnState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("State");

        javax.swing.GroupLayout btnStateLayout = new javax.swing.GroupLayout(btnState);
        btnState.setLayout(btnStateLayout);
        btnStateLayout.setHorizontalGroup(
            btnStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnStateLayout.setVerticalGroup(
            btnStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnState, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 141, 50));

        btnChainOR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("<html>Chain Of Responsability<html>");

        javax.swing.GroupLayout btnChainORLayout = new javax.swing.GroupLayout(btnChainOR);
        btnChainOR.setLayout(btnChainORLayout);
        btnChainORLayout.setHorizontalGroup(
            btnChainORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnChainORLayout.setVerticalGroup(
            btnChainORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnChainOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 141, 50));

        btnCommand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Command");

        javax.swing.GroupLayout btnCommandLayout = new javax.swing.GroupLayout(btnCommand);
        btnCommand.setLayout(btnCommandLayout);
        btnCommandLayout.setHorizontalGroup(
            btnCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCommandLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCommandLayout.setVerticalGroup(
            btnCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCommand, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 141, 50));

        btnIterator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Iterator");

        javax.swing.GroupLayout btnIteratorLayout = new javax.swing.GroupLayout(btnIterator);
        btnIterator.setLayout(btnIteratorLayout);
        btnIteratorLayout.setHorizontalGroup(
            btnIteratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnIteratorLayout.setVerticalGroup(
            btnIteratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnIterator, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 141, 50));

        btnMediator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mediator");

        javax.swing.GroupLayout btnMediatorLayout = new javax.swing.GroupLayout(btnMediator);
        btnMediator.setLayout(btnMediatorLayout);
        btnMediatorLayout.setHorizontalGroup(
            btnMediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMediatorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMediatorLayout.setVerticalGroup(
            btnMediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMediator, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 141, 50));

        btnMemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Memento");

        javax.swing.GroupLayout btnMementoLayout = new javax.swing.GroupLayout(btnMemento);
        btnMemento.setLayout(btnMementoLayout);
        btnMementoLayout.setHorizontalGroup(
            btnMementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMementoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMementoLayout.setVerticalGroup(
            btnMementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 141, 50));

        btnProxy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Proxy");

        javax.swing.GroupLayout btnProxyLayout = new javax.swing.GroupLayout(btnProxy);
        btnProxy.setLayout(btnProxyLayout);
        btnProxyLayout.setHorizontalGroup(
            btnProxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProxyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnProxyLayout.setVerticalGroup(
            btnProxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnProxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 141, 50));

        btnFlyweight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Flyweight ");

        javax.swing.GroupLayout btnFlyweightLayout = new javax.swing.GroupLayout(btnFlyweight);
        btnFlyweight.setLayout(btnFlyweightLayout);
        btnFlyweightLayout.setHorizontalGroup(
            btnFlyweightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFlyweightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFlyweightLayout.setVerticalGroup(
            btnFlyweightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnFlyweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 141, 50));

        btnFacade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Facade");

        javax.swing.GroupLayout btnFacadeLayout = new javax.swing.GroupLayout(btnFacade);
        btnFacade.setLayout(btnFacadeLayout);
        btnFacadeLayout.setHorizontalGroup(
            btnFacadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFacadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFacadeLayout.setVerticalGroup(
            btnFacadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnFacade, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 141, 50));

        btnDecorator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Decorator");

        javax.swing.GroupLayout btnDecoratorLayout = new javax.swing.GroupLayout(btnDecorator);
        btnDecorator.setLayout(btnDecoratorLayout);
        btnDecoratorLayout.setHorizontalGroup(
            btnDecoratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDecoratorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDecoratorLayout.setVerticalGroup(
            btnDecoratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnDecorator, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 141, 50));

        btnComposite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Composite");

        javax.swing.GroupLayout btnCompositeLayout = new javax.swing.GroupLayout(btnComposite);
        btnComposite.setLayout(btnCompositeLayout);
        btnCompositeLayout.setHorizontalGroup(
            btnCompositeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnCompositeLayout.setVerticalGroup(
            btnCompositeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnComposite, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 141, 50));

        btnBridge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bridge");

        javax.swing.GroupLayout btnBridgeLayout = new javax.swing.GroupLayout(btnBridge);
        btnBridge.setLayout(btnBridgeLayout);
        btnBridgeLayout.setHorizontalGroup(
            btnBridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBridgeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBridgeLayout.setVerticalGroup(
            btnBridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnBridge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 141, 50));

        btnAdapter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Adapter");

        javax.swing.GroupLayout btnAdapterLayout = new javax.swing.GroupLayout(btnAdapter);
        btnAdapter.setLayout(btnAdapterLayout);
        btnAdapterLayout.setHorizontalGroup(
            btnAdapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnAdapterLayout.setVerticalGroup(
            btnAdapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnAdapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 141, 50));

        btnSingleton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Singleton");

        javax.swing.GroupLayout btnSingletonLayout = new javax.swing.GroupLayout(btnSingleton);
        btnSingleton.setLayout(btnSingletonLayout);
        btnSingletonLayout.setHorizontalGroup(
            btnSingletonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSingletonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSingletonLayout.setVerticalGroup(
            btnSingletonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnSingleton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 141, 50));

        btnPrototype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prototype");

        javax.swing.GroupLayout btnPrototypeLayout = new javax.swing.GroupLayout(btnPrototype);
        btnPrototype.setLayout(btnPrototypeLayout);
        btnPrototypeLayout.setHorizontalGroup(
            btnPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPrototypeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPrototypeLayout.setVerticalGroup(
            btnPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnPrototype, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 141, 50));

        btnBuilder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Builder");

        javax.swing.GroupLayout btnBuilderLayout = new javax.swing.GroupLayout(btnBuilder);
        btnBuilder.setLayout(btnBuilderLayout);
        btnBuilderLayout.setHorizontalGroup(
            btnBuilderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnBuilderLayout.setVerticalGroup(
            btnBuilderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuilder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 141, 50));

        btnAbstractF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Abstract Factory");

        javax.swing.GroupLayout btnAbstractFLayout = new javax.swing.GroupLayout(btnAbstractF);
        btnAbstractF.setLayout(btnAbstractFLayout);
        btnAbstractFLayout.setHorizontalGroup(
            btnAbstractFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAbstractFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAbstractFLayout.setVerticalGroup(
            btnAbstractFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnAbstractF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 141, 50));

        btnFactoryM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Factory Method<html>");

        javax.swing.GroupLayout btnFactoryMLayout = new javax.swing.GroupLayout(btnFactoryM);
        btnFactoryM.setLayout(btnFactoryMLayout);
        btnFactoryMLayout.setHorizontalGroup(
            btnFactoryMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFactoryMLayout.setVerticalGroup(
            btnFactoryMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnFactoryM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 141, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons/Home/bgCircle.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 510, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons/Home/bgTriangle.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 530, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LblDefinition;
    private javax.swing.JLabel LblSubtittle1;
    private javax.swing.JLabel LblSubtittle2;
    private javax.swing.JLabel LblSubtittle3;
    private javax.swing.JLabel LblTittle;
    private javax.swing.JPanel bgDecoration1;
    private javax.swing.JPanel btnAbstractF;
    private javax.swing.JPanel btnAdapter;
    private javax.swing.JPanel btnBridge;
    private javax.swing.JPanel btnBuilder;
    private javax.swing.JPanel btnChainOR;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnCommand;
    private javax.swing.JPanel btnComposite;
    private javax.swing.JPanel btnDecorator;
    private javax.swing.JPanel btnFacade;
    private javax.swing.JPanel btnFactoryM;
    private javax.swing.JPanel btnFlyweight;
    private javax.swing.JPanel btnGlossary;
    private javax.swing.JPanel btnIterator;
    private javax.swing.JPanel btnMediator;
    private javax.swing.JPanel btnMemento;
    private javax.swing.JPanel btnObserver;
    private javax.swing.JPanel btnPrototype;
    private javax.swing.JPanel btnProxy;
    private javax.swing.JPanel btnSingleton;
    private javax.swing.JPanel btnState;
    private javax.swing.JPanel btnStrategy;
    private javax.swing.JPanel btnTemplateM;
    private javax.swing.JPanel btnVisitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
