/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.parser.ParseException;

public class Home extends javax.swing.JFrame {
    int mouseX,mouseY;
    PatternX newFrame;
    
    public Home() throws IOException, FileNotFoundException, ParseException {
        initComponents();
        newFrame = new PatternX();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        bgDecoration1 = new javax.swing.JPanel();
        LblTittle = new javax.swing.JLabel();
        LblDefinition = new javax.swing.JLabel();
        LblSubtittle1 = new javax.swing.JLabel();
        LblSubtittle2 = new javax.swing.JLabel();
        LblSubtittle3 = new javax.swing.JLabel();
        btnGlossary = new javax.swing.JPanel();
        LblGlossary = new javax.swing.JLabel();
        btnObserver = new javax.swing.JPanel();
        LblObserver = new javax.swing.JLabel();
        btnStrategy = new javax.swing.JPanel();
        LblStrategy = new javax.swing.JLabel();
        btnTemplateM = new javax.swing.JPanel();
        LblTemplateMethod = new javax.swing.JLabel();
        btnVisitor = new javax.swing.JPanel();
        LblVisitor = new javax.swing.JLabel();
        btnState = new javax.swing.JPanel();
        LblState = new javax.swing.JLabel();
        btnChainOR = new javax.swing.JPanel();
        LblChainOfResponsability = new javax.swing.JLabel();
        btnCommand = new javax.swing.JPanel();
        LblCommand = new javax.swing.JLabel();
        btnIterator = new javax.swing.JPanel();
        LblIterator = new javax.swing.JLabel();
        btnMediator = new javax.swing.JPanel();
        LblMediator = new javax.swing.JLabel();
        btnMemento = new javax.swing.JPanel();
        LblMemento = new javax.swing.JLabel();
        btnProxy = new javax.swing.JPanel();
        LblProxy = new javax.swing.JLabel();
        btnFlyweight = new javax.swing.JPanel();
        LblFlyweight = new javax.swing.JLabel();
        btnFacade = new javax.swing.JPanel();
        LblFacade = new javax.swing.JLabel();
        btnDecorator = new javax.swing.JPanel();
        LblDecorator = new javax.swing.JLabel();
        btnComposite = new javax.swing.JPanel();
        LblComposite = new javax.swing.JLabel();
        btnBridge = new javax.swing.JPanel();
        LblBridge = new javax.swing.JLabel();
        btnAdapter = new javax.swing.JPanel();
        LblAdapter = new javax.swing.JLabel();
        btnSingleton = new javax.swing.JPanel();
        LblSingleton = new javax.swing.JLabel();
        btnPrototype = new javax.swing.JPanel();
        LblPrototype = new javax.swing.JLabel();
        btnBuilder = new javax.swing.JPanel();
        LblBuilder = new javax.swing.JLabel();
        btnAbstractF = new javax.swing.JPanel();
        LblAbstractFactory = new javax.swing.JLabel();
        btnFactoryM = new javax.swing.JPanel();
        LblFactoryMethod = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 3));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 50));

        bgDecoration1.setBackground(new java.awt.Color(253, 196, 196));

        LblTittle.setFont(new java.awt.Font("Instrument Sans", 1, 36)); // NOI18N
        LblTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTittle.setText("Patrones de Diseño");

        javax.swing.GroupLayout bgDecoration1Layout = new javax.swing.GroupLayout(bgDecoration1);
        bgDecoration1.setLayout(bgDecoration1Layout);
        bgDecoration1Layout.setHorizontalGroup(
            bgDecoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDecoration1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(LblTittle)
                .addGap(52, 52, 52))
        );
        bgDecoration1Layout.setVerticalGroup(
            bgDecoration1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDecoration1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(LblTittle)
                .addContainerGap())
        );

        jPanel1.add(bgDecoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 51, 442, 60));

        LblDefinition.setFont(new java.awt.Font("Instrument Sans", 0, 17)); // NOI18N
        LblDefinition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDefinition.setText("<html>Los patrones de diseño son enfoques estándar para resolver problemas comunes en el desarrollo de software. Funcionan como esquemas o guías que pueden adaptarse a las necesidades específicas de un proyecto, ayudando a abordar situaciones recurrentes en el diseño del código. A diferencia de funciones o bibliotecas predefinidas, no se pueden copiar directamente en el programa. En su lugar, un patrón es una idea general que se implementa de acuerdo con las características y requisitos particulares del sistema en desarrollo, ofreciendo una solución flexible y ajustable al problema en cuestión.<html>");
        jPanel1.add(LblDefinition, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 800, 146));

        LblSubtittle1.setFont(new java.awt.Font("Instrument Sans", 1, 24)); // NOI18N
        LblSubtittle1.setText("Comportamentales");
        jPanel1.add(LblSubtittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        LblSubtittle2.setFont(new java.awt.Font("Instrument Sans", 1, 24)); // NOI18N
        LblSubtittle2.setText("Creacionales");
        jPanel1.add(LblSubtittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        LblSubtittle3.setFont(new java.awt.Font("Instrument Sans", 1, 24)); // NOI18N
        LblSubtittle3.setText("Estructurales");
        jPanel1.add(LblSubtittle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        btnGlossary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblGlossary.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblGlossary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblGlossary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Glossary_Icon.png"))); // NOI18N
        LblGlossary.setText("Glosario");
        LblGlossary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblGlossaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblGlossaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblGlossaryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGlossaryLayout = new javax.swing.GroupLayout(btnGlossary);
        btnGlossary.setLayout(btnGlossaryLayout);
        btnGlossaryLayout.setHorizontalGroup(
            btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnGlossaryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LblGlossary, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnGlossaryLayout.setVerticalGroup(
            btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnGlossaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnGlossaryLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LblGlossary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnGlossary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 141, 50));

        btnObserver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblObserver.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblObserver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblObserver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/observer_Icon.png"))); // NOI18N
        LblObserver.setText("Observer");
        LblObserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblObserverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblObserverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblObserverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnObserverLayout = new javax.swing.GroupLayout(btnObserver);
        btnObserver.setLayout(btnObserverLayout);
        btnObserverLayout.setHorizontalGroup(
            btnObserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblObserver, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnObserverLayout.setVerticalGroup(
            btnObserverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblObserver, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnObserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 141, 50));

        btnStrategy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblStrategy.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblStrategy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblStrategy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Strategy_Icon.png"))); // NOI18N
        LblStrategy.setText("Strategy");
        LblStrategy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblStrategyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblStrategyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblStrategyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnStrategyLayout = new javax.swing.GroupLayout(btnStrategy);
        btnStrategy.setLayout(btnStrategyLayout);
        btnStrategyLayout.setHorizontalGroup(
            btnStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStrategyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnStrategyLayout.setVerticalGroup(
            btnStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblStrategy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnStrategy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 141, 50));

        btnTemplateM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblTemplateMethod.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblTemplateMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTemplateMethod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/TemplateMethod_Icon.png"))); // NOI18N
        LblTemplateMethod.setText("<html>Template Method<html>");
        LblTemplateMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblTemplateMethodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblTemplateMethodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblTemplateMethodMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTemplateMLayout = new javax.swing.GroupLayout(btnTemplateM);
        btnTemplateM.setLayout(btnTemplateMLayout);
        btnTemplateMLayout.setHorizontalGroup(
            btnTemplateMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblTemplateMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnTemplateMLayout.setVerticalGroup(
            btnTemplateMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblTemplateMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnTemplateM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 141, 50));

        btnVisitor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblVisitor.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblVisitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblVisitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Visitor_Icon.png"))); // NOI18N
        LblVisitor.setText("Visitor");
        LblVisitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblVisitorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblVisitorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblVisitorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVisitorLayout = new javax.swing.GroupLayout(btnVisitor);
        btnVisitor.setLayout(btnVisitorLayout);
        btnVisitorLayout.setHorizontalGroup(
            btnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisitorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnVisitorLayout.setVerticalGroup(
            btnVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblVisitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 141, 50));

        btnState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblState.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/State_Icon.png"))); // NOI18N
        LblState.setText("State");
        LblState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblStateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblStateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnStateLayout = new javax.swing.GroupLayout(btnState);
        btnState.setLayout(btnStateLayout);
        btnStateLayout.setHorizontalGroup(
            btnStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblState, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnStateLayout.setVerticalGroup(
            btnStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnState, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 141, 50));

        btnChainOR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblChainOfResponsability.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblChainOfResponsability.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblChainOfResponsability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/ChainOfResponsability_Icon.png"))); // NOI18N
        LblChainOfResponsability.setText("<html>Chain Of Responsability<html>");
        LblChainOfResponsability.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblChainOfResponsabilityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblChainOfResponsabilityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblChainOfResponsabilityMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnChainORLayout = new javax.swing.GroupLayout(btnChainOR);
        btnChainOR.setLayout(btnChainORLayout);
        btnChainORLayout.setHorizontalGroup(
            btnChainORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblChainOfResponsability, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnChainORLayout.setVerticalGroup(
            btnChainORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblChainOfResponsability, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnChainOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 141, 50));

        btnCommand.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblCommand.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblCommand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCommand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Command_Icon.png"))); // NOI18N
        LblCommand.setText("Command");
        LblCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCommandMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblCommandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblCommandMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCommandLayout = new javax.swing.GroupLayout(btnCommand);
        btnCommand.setLayout(btnCommandLayout);
        btnCommandLayout.setHorizontalGroup(
            btnCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCommandLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCommandLayout.setVerticalGroup(
            btnCommandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblCommand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCommand, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 141, 50));

        btnIterator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblIterator.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblIterator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblIterator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/iteration_Icon.png"))); // NOI18N
        LblIterator.setText("Iterator");
        LblIterator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblIteratorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblIteratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblIteratorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnIteratorLayout = new javax.swing.GroupLayout(btnIterator);
        btnIterator.setLayout(btnIteratorLayout);
        btnIteratorLayout.setHorizontalGroup(
            btnIteratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblIterator, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnIteratorLayout.setVerticalGroup(
            btnIteratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblIterator, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnIterator, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 141, 50));

        btnMediator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblMediator.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblMediator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMediator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/mediator_Icon.png"))); // NOI18N
        LblMediator.setText("Mediator");
        LblMediator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMediatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMediatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMediatorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMediatorLayout = new javax.swing.GroupLayout(btnMediator);
        btnMediator.setLayout(btnMediatorLayout);
        btnMediatorLayout.setHorizontalGroup(
            btnMediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMediatorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblMediator, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMediatorLayout.setVerticalGroup(
            btnMediatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblMediator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMediator, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 141, 50));

        btnMemento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblMemento.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblMemento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Memento_Icon.png"))); // NOI18N
        LblMemento.setText("Memento");
        LblMemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMementoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblMementoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblMementoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMementoLayout = new javax.swing.GroupLayout(btnMemento);
        btnMemento.setLayout(btnMementoLayout);
        btnMementoLayout.setHorizontalGroup(
            btnMementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMementoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblMemento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMementoLayout.setVerticalGroup(
            btnMementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblMemento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnMemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 141, 50));

        btnProxy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblProxy.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblProxy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblProxy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Proxy_Icon.png"))); // NOI18N
        LblProxy.setText("Proxy");
        LblProxy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblProxyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblProxyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblProxyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnProxyLayout = new javax.swing.GroupLayout(btnProxy);
        btnProxy.setLayout(btnProxyLayout);
        btnProxyLayout.setHorizontalGroup(
            btnProxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProxyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblProxy, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnProxyLayout.setVerticalGroup(
            btnProxyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblProxy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnProxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 141, 50));

        btnFlyweight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblFlyweight.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblFlyweight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFlyweight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Flightweight_Icon.png"))); // NOI18N
        LblFlyweight.setText("Flyweight");
        LblFlyweight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFlyweightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblFlyweightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblFlyweightMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFlyweightLayout = new javax.swing.GroupLayout(btnFlyweight);
        btnFlyweight.setLayout(btnFlyweightLayout);
        btnFlyweightLayout.setHorizontalGroup(
            btnFlyweightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFlyweightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblFlyweight, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFlyweightLayout.setVerticalGroup(
            btnFlyweightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFlyweight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnFlyweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 141, 50));

        btnFacade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblFacade.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblFacade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFacade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Facade_Icon.png"))); // NOI18N
        LblFacade.setText("Facade");
        LblFacade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFacadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblFacadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblFacadeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFacadeLayout = new javax.swing.GroupLayout(btnFacade);
        btnFacade.setLayout(btnFacadeLayout);
        btnFacadeLayout.setHorizontalGroup(
            btnFacadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFacadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblFacade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnFacadeLayout.setVerticalGroup(
            btnFacadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFacade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnFacade, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 141, 50));

        btnDecorator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblDecorator.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblDecorator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDecorator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Decorator_Icon.png"))); // NOI18N
        LblDecorator.setText("Decorator");
        LblDecorator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDecoratorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblDecoratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblDecoratorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDecoratorLayout = new javax.swing.GroupLayout(btnDecorator);
        btnDecorator.setLayout(btnDecoratorLayout);
        btnDecoratorLayout.setHorizontalGroup(
            btnDecoratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDecoratorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblDecorator, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDecoratorLayout.setVerticalGroup(
            btnDecoratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblDecorator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnDecorator, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 141, 50));

        btnComposite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblComposite.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblComposite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblComposite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Composite_Icon.png"))); // NOI18N
        LblComposite.setText("Composite");
        LblComposite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCompositeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblCompositeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblCompositeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCompositeLayout = new javax.swing.GroupLayout(btnComposite);
        btnComposite.setLayout(btnCompositeLayout);
        btnCompositeLayout.setHorizontalGroup(
            btnCompositeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblComposite, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnCompositeLayout.setVerticalGroup(
            btnCompositeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblComposite, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnComposite, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 141, 50));

        btnBridge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblBridge.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblBridge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblBridge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Bridge_Icon.png"))); // NOI18N
        LblBridge.setText("Bridge");
        LblBridge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblBridgeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblBridgeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblBridgeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBridgeLayout = new javax.swing.GroupLayout(btnBridge);
        btnBridge.setLayout(btnBridgeLayout);
        btnBridgeLayout.setHorizontalGroup(
            btnBridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBridgeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblBridge, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnBridgeLayout.setVerticalGroup(
            btnBridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblBridge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnBridge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 141, 50));

        btnAdapter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAdapter.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblAdapter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblAdapter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Adapter_Icon.png"))); // NOI18N
        LblAdapter.setText("Adapter");
        LblAdapter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblAdapterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblAdapterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblAdapterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAdapterLayout = new javax.swing.GroupLayout(btnAdapter);
        btnAdapter.setLayout(btnAdapterLayout);
        btnAdapterLayout.setHorizontalGroup(
            btnAdapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblAdapter, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnAdapterLayout.setVerticalGroup(
            btnAdapterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblAdapter, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnAdapter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 141, 50));

        btnSingleton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblSingleton.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblSingleton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSingleton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Singleton_Icon.png"))); // NOI18N
        LblSingleton.setText("Singleton");
        LblSingleton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblSingletonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblSingletonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblSingletonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSingletonLayout = new javax.swing.GroupLayout(btnSingleton);
        btnSingleton.setLayout(btnSingletonLayout);
        btnSingletonLayout.setHorizontalGroup(
            btnSingletonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSingletonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblSingleton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnSingletonLayout.setVerticalGroup(
            btnSingletonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblSingleton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnSingleton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 141, 50));

        btnPrototype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblPrototype.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblPrototype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPrototype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Prototype_Icon.png"))); // NOI18N
        LblPrototype.setText("Prototype");
        LblPrototype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPrototypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblPrototypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblPrototypeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPrototypeLayout = new javax.swing.GroupLayout(btnPrototype);
        btnPrototype.setLayout(btnPrototypeLayout);
        btnPrototypeLayout.setHorizontalGroup(
            btnPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPrototypeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblPrototype, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPrototypeLayout.setVerticalGroup(
            btnPrototypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblPrototype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnPrototype, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 141, 50));

        btnBuilder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblBuilder.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblBuilder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblBuilder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/Builder_Icon.png"))); // NOI18N
        LblBuilder.setText("Builder");
        LblBuilder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblBuilderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblBuilderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblBuilderMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuilderLayout = new javax.swing.GroupLayout(btnBuilder);
        btnBuilder.setLayout(btnBuilderLayout);
        btnBuilderLayout.setHorizontalGroup(
            btnBuilderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblBuilder, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        btnBuilderLayout.setVerticalGroup(
            btnBuilderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblBuilder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuilder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 141, 50));

        btnAbstractF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAbstractFactory.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblAbstractFactory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblAbstractFactory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/AbstracFactory_Icon.png"))); // NOI18N
        LblAbstractFactory.setText("<html>Abstract Factory<html>");
        LblAbstractFactory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblAbstractFactoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblAbstractFactoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblAbstractFactoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAbstractFLayout = new javax.swing.GroupLayout(btnAbstractF);
        btnAbstractF.setLayout(btnAbstractFLayout);
        btnAbstractFLayout.setHorizontalGroup(
            btnAbstractFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAbstractFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblAbstractFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAbstractFLayout.setVerticalGroup(
            btnAbstractFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblAbstractFactory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnAbstractF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 141, 50));

        btnFactoryM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblFactoryMethod.setFont(new java.awt.Font("Instrument Sans", 0, 14)); // NOI18N
        LblFactoryMethod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFactoryMethod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/FactoryMethod_Icon.png"))); // NOI18N
        LblFactoryMethod.setText("<html>Factory  Method<html>");
        LblFactoryMethod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFactoryMethodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblFactoryMethodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblFactoryMethodMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnFactoryMLayout = new javax.swing.GroupLayout(btnFactoryM);
        btnFactoryM.setLayout(btnFactoryMLayout);
        btnFactoryMLayout.setHorizontalGroup(
            btnFactoryMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFactoryMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFactoryMLayout.setVerticalGroup(
            btnFactoryMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFactoryMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnFactoryM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 141, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/bgCircle.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 510, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Home/bgTriangle.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 530, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void LblFactoryMethodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFactoryMethodMouseClicked
        newFrame.setDato(LblFactoryMethod.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblFactoryMethodMouseClicked

    private void LblFactoryMethodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFactoryMethodMouseEntered
        btnFactoryM.setOpaque(true);
        btnFactoryM.setBackground(Color.gray);
       
    }//GEN-LAST:event_LblFactoryMethodMouseEntered

    private void LblFactoryMethodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFactoryMethodMouseExited
        btnFactoryM.setOpaque(true);
        btnFactoryM.setBackground(new Color(214, 217, 223));
        
    }//GEN-LAST:event_LblFactoryMethodMouseExited

    private void LblAbstractFactoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAbstractFactoryMouseClicked
        newFrame.setDato(LblAbstractFactory.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblAbstractFactoryMouseClicked

    private void LblAbstractFactoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAbstractFactoryMouseEntered
        btnAbstractF.setOpaque(true);
        btnAbstractF.setBackground(Color.gray);
    }//GEN-LAST:event_LblAbstractFactoryMouseEntered

    private void LblAbstractFactoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAbstractFactoryMouseExited
        btnAbstractF.setOpaque(true);
        btnAbstractF.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblAbstractFactoryMouseExited

    private void LblBuilderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBuilderMouseClicked
        newFrame.setDato(LblBuilder.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblBuilderMouseClicked

    private void LblBuilderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBuilderMouseEntered
        btnBuilder.setOpaque(true);
        btnBuilder.setBackground(Color.gray);
    }//GEN-LAST:event_LblBuilderMouseEntered

    private void LblBuilderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBuilderMouseExited
        btnBuilder.setOpaque(true);
        btnBuilder.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblBuilderMouseExited

    private void LblPrototypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPrototypeMouseClicked
        newFrame.setDato(LblPrototype.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblPrototypeMouseClicked

    private void LblPrototypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPrototypeMouseEntered
        btnPrototype.setOpaque(true);
        btnPrototype.setBackground(Color.gray);
    }//GEN-LAST:event_LblPrototypeMouseEntered

    private void LblPrototypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPrototypeMouseExited
        btnPrototype.setOpaque(true);
        btnPrototype.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblPrototypeMouseExited

    private void LblSingletonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSingletonMouseClicked
        newFrame.setDato(LblSingleton.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblSingletonMouseClicked

    private void LblSingletonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSingletonMouseEntered
        btnSingleton.setOpaque(true);
        btnSingleton.setBackground(Color.gray);
    }//GEN-LAST:event_LblSingletonMouseEntered

    private void LblSingletonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSingletonMouseExited
        btnSingleton.setOpaque(true);
        btnSingleton.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblSingletonMouseExited

    private void LblGlossaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGlossaryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblGlossaryMouseClicked

    private void LblGlossaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGlossaryMouseEntered
        btnGlossary.setOpaque(true);
        btnGlossary.setBackground(Color.gray);
    }//GEN-LAST:event_LblGlossaryMouseEntered

    private void LblGlossaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblGlossaryMouseExited
        btnGlossary.setOpaque(true);
        btnGlossary.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblGlossaryMouseExited

    private void LblAdapterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdapterMouseClicked
        newFrame.setDato(LblAdapter.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblAdapterMouseClicked

    private void LblAdapterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdapterMouseEntered
        btnAdapter.setOpaque(true);
        btnAdapter.setBackground(Color.gray);
    }//GEN-LAST:event_LblAdapterMouseEntered

    private void LblAdapterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdapterMouseExited
        btnAdapter.setOpaque(true);
        btnAdapter.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblAdapterMouseExited

    private void LblBridgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBridgeMouseClicked
        newFrame.setDato(LblBridge.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblBridgeMouseClicked

    private void LblBridgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBridgeMouseEntered
        btnBridge.setOpaque(true);
        btnBridge.setBackground(Color.gray);
    }//GEN-LAST:event_LblBridgeMouseEntered

    private void LblBridgeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBridgeMouseExited
        btnBridge.setOpaque(true);
        btnBridge.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblBridgeMouseExited

    private void LblCompositeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCompositeMouseClicked
        newFrame.setDato(LblComposite.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblCompositeMouseClicked

    private void LblCompositeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCompositeMouseEntered
        btnComposite.setOpaque(true);
        btnComposite.setBackground(Color.gray);
    }//GEN-LAST:event_LblCompositeMouseEntered

    private void LblCompositeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCompositeMouseExited
        btnComposite.setOpaque(true);
        btnComposite.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblCompositeMouseExited

    private void LblDecoratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDecoratorMouseClicked
        newFrame.setDato(LblDecorator.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblDecoratorMouseClicked

    private void LblDecoratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDecoratorMouseEntered
        btnDecorator.setOpaque(true);
        btnDecorator.setBackground(Color.gray);
    }//GEN-LAST:event_LblDecoratorMouseEntered

    private void LblDecoratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDecoratorMouseExited
        btnDecorator.setOpaque(true);
        btnDecorator.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblDecoratorMouseExited

    private void LblFacadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFacadeMouseClicked
        newFrame.setDato(LblFacade.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblFacadeMouseClicked

    private void LblFacadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFacadeMouseEntered
        btnFacade.setOpaque(true);
        btnFacade.setBackground(Color.gray);
    }//GEN-LAST:event_LblFacadeMouseEntered

    private void LblFacadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFacadeMouseExited
        btnFacade.setOpaque(true);
        btnFacade.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblFacadeMouseExited

    private void LblFlyweightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFlyweightMouseClicked
        newFrame.setDato(LblFlyweight.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblFlyweightMouseClicked

    private void LblFlyweightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFlyweightMouseEntered
        btnFlyweight.setOpaque(true);
        btnFlyweight.setBackground(Color.gray);
    }//GEN-LAST:event_LblFlyweightMouseEntered

    private void LblFlyweightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFlyweightMouseExited
        btnFlyweight.setOpaque(true);
        btnFlyweight.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblFlyweightMouseExited

    private void LblProxyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblProxyMouseClicked
        newFrame.setDato(LblProxy.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblProxyMouseClicked

    private void LblProxyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblProxyMouseEntered
        btnProxy.setOpaque(true);
        btnProxy.setBackground(Color.gray);
    }//GEN-LAST:event_LblProxyMouseEntered

    private void LblProxyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblProxyMouseExited
        btnProxy.setOpaque(true);
        btnProxy.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblProxyMouseExited

    private void LblChainOfResponsabilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblChainOfResponsabilityMouseClicked
        newFrame.setDato(LblChainOfResponsability.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblChainOfResponsabilityMouseClicked

    private void LblChainOfResponsabilityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblChainOfResponsabilityMouseEntered
        btnChainOR.setOpaque(true);
        btnChainOR.setBackground(Color.gray);
    }//GEN-LAST:event_LblChainOfResponsabilityMouseEntered

    private void LblChainOfResponsabilityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblChainOfResponsabilityMouseExited
        btnChainOR.setOpaque(true);
        btnChainOR.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblChainOfResponsabilityMouseExited

    private void LblCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCommandMouseClicked
        newFrame.setDato(LblCommand.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblCommandMouseClicked

    private void LblCommandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCommandMouseEntered
        btnCommand.setOpaque(true);
        btnCommand.setBackground(Color.gray);
    }//GEN-LAST:event_LblCommandMouseEntered

    private void LblCommandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCommandMouseExited
        btnCommand.setOpaque(true);
        btnCommand.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblCommandMouseExited

    private void LblIteratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblIteratorMouseClicked
        newFrame.setDato(LblIterator.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblIteratorMouseClicked

    private void LblIteratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblIteratorMouseEntered
        btnIterator.setOpaque(true);
        btnIterator.setBackground(Color.gray);
    }//GEN-LAST:event_LblIteratorMouseEntered

    private void LblIteratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblIteratorMouseExited
        btnIterator.setOpaque(true);
        btnIterator.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblIteratorMouseExited

    private void LblMediatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMediatorMouseClicked
        newFrame.setDato(LblMediator.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblMediatorMouseClicked

    private void LblMediatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMediatorMouseEntered
        btnMediator.setOpaque(true);
        btnMediator.setBackground(Color.gray);
    }//GEN-LAST:event_LblMediatorMouseEntered

    private void LblMediatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMediatorMouseExited
        btnMediator.setOpaque(true);
        btnMediator.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblMediatorMouseExited

    private void LblMementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMementoMouseClicked
        newFrame.setDato(LblMemento.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblMementoMouseClicked

    private void LblMementoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMementoMouseEntered
        btnMemento.setOpaque(true);
        btnMemento.setBackground(Color.gray);
    }//GEN-LAST:event_LblMementoMouseEntered

    private void LblMementoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMementoMouseExited
        btnMemento.setOpaque(true);
        btnMemento.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblMementoMouseExited

    private void LblObserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblObserverMouseClicked
        newFrame.setDato(LblObserver.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblObserverMouseClicked

    private void LblObserverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblObserverMouseEntered
        btnObserver.setOpaque(true);
        btnObserver.setBackground(Color.gray);
    }//GEN-LAST:event_LblObserverMouseEntered

    private void LblObserverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblObserverMouseExited
        btnObserver.setOpaque(true);
        btnObserver.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblObserverMouseExited

    private void LblStrategyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStrategyMouseClicked
        newFrame.setDato(LblStrategy.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblStrategyMouseClicked

    private void LblStrategyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStrategyMouseEntered
        btnStrategy.setOpaque(true);
        btnStrategy.setBackground(Color.gray);
    }//GEN-LAST:event_LblStrategyMouseEntered

    private void LblStrategyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStrategyMouseExited
        btnStrategy.setOpaque(true);
        btnStrategy.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblStrategyMouseExited

    private void LblTemplateMethodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTemplateMethodMouseClicked
        newFrame.setDato(LblTemplateMethod.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblTemplateMethodMouseClicked

    private void LblTemplateMethodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTemplateMethodMouseEntered
        btnTemplateM.setOpaque(true);
        btnTemplateM.setBackground(Color.gray);
    }//GEN-LAST:event_LblTemplateMethodMouseEntered

    private void LblTemplateMethodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblTemplateMethodMouseExited
        btnTemplateM.setOpaque(true);
        btnTemplateM.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblTemplateMethodMouseExited

    private void LblVisitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblVisitorMouseClicked
        newFrame.setDato(LblVisitor.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblVisitorMouseClicked

    private void LblVisitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblVisitorMouseEntered
        btnVisitor.setOpaque(true);
        btnVisitor.setBackground(Color.gray);
    }//GEN-LAST:event_LblVisitorMouseEntered

    private void LblVisitorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblVisitorMouseExited
        btnVisitor.setOpaque(true);
        btnVisitor.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblVisitorMouseExited

    private void LblStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStateMouseClicked
        newFrame.setDato(LblState.getText());
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblStateMouseClicked

    private void LblStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStateMouseEntered
        btnState.setOpaque(true);
        btnState.setBackground(Color.gray);
    }//GEN-LAST:event_LblStateMouseEntered

    private void LblStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblStateMouseExited
        btnState.setOpaque(true);
        btnState.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_LblStateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LblAbstractFactory;
    private javax.swing.JLabel LblAdapter;
    private javax.swing.JLabel LblBridge;
    private javax.swing.JLabel LblBuilder;
    private javax.swing.JLabel LblChainOfResponsability;
    private javax.swing.JLabel LblCommand;
    private javax.swing.JLabel LblComposite;
    private javax.swing.JLabel LblDecorator;
    private javax.swing.JLabel LblDefinition;
    private javax.swing.JLabel LblFacade;
    private javax.swing.JLabel LblFactoryMethod;
    private javax.swing.JLabel LblFlyweight;
    private javax.swing.JLabel LblGlossary;
    private javax.swing.JLabel LblIterator;
    private javax.swing.JLabel LblMediator;
    private javax.swing.JLabel LblMemento;
    private javax.swing.JLabel LblObserver;
    private javax.swing.JLabel LblPrototype;
    private javax.swing.JLabel LblProxy;
    private javax.swing.JLabel LblSingleton;
    private javax.swing.JLabel LblState;
    private javax.swing.JLabel LblStrategy;
    private javax.swing.JLabel LblSubtittle1;
    private javax.swing.JLabel LblSubtittle2;
    private javax.swing.JLabel LblSubtittle3;
    private javax.swing.JLabel LblTemplateMethod;
    private javax.swing.JLabel LblTittle;
    private javax.swing.JLabel LblVisitor;
    private javax.swing.JPanel bgDecoration1;
    private javax.swing.JPanel btnAbstractF;
    private javax.swing.JPanel btnAdapter;
    private javax.swing.JPanel btnBridge;
    private javax.swing.JPanel btnBuilder;
    private javax.swing.JPanel btnChainOR;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnCommand;
    private javax.swing.JPanel btnComposite;
    private javax.swing.JPanel btnDecorator;
    private javax.swing.JPanel btnFacade;
    private javax.swing.JPanel btnFactoryM;
    private javax.swing.JPanel btnFlyweight;
    private javax.swing.JPanel btnGlossary;
    private javax.swing.JPanel btnIterator;
    private javax.swing.JPanel btnMediator;
    private javax.swing.JPanel btnMemento;
    private javax.swing.JPanel btnObserver;
    private javax.swing.JPanel btnPrototype;
    private javax.swing.JPanel btnProxy;
    private javax.swing.JPanel btnSingleton;
    private javax.swing.JPanel btnState;
    private javax.swing.JPanel btnStrategy;
    private javax.swing.JPanel btnTemplateM;
    private javax.swing.JPanel btnVisitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
