/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Observer extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    int levelE1=0,levelE2=0, levelE3=0;
    
    public Observer() {
        initComponents();
        decorator();
        calcularNivel(cmbWorldLevel.getSelectedIndex()+1);
        
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        setImageLabel(lblWorld,"src/Assets/IMG/Observer/World_Img.png");
        setImageLabel(lblEnemy1,"src/Assets/IMG/Observer/Enemy1_Img.png");
        setImageLabel(lblEnemy2,"src/Assets/IMG/Observer/Enemy2_Img.png");
        setImageLabel(lblEnemy3,"src/Assets/IMG/Observer/Enemy3_Img.png");
        lblTittle1.setFont(typeFont.fontV(typeFont.instruments, 1, 14));
        lblTittle2.setFont(typeFont.fontV(typeFont.instruments, 1, 14));
        lblSubtittle.setFont(typeFont.fontV(typeFont.instruments, 0, 14));
        lblText.setFont(typeFont.fontV(typeFont.instruments, 0, 14));
        
    }
    
    private void calcularNivel(int worldLevel){
          levelE1=(worldLevel * 4) * 2;
          levelE2=(worldLevel * 4) * 3;
          levelE3=(worldLevel * 4) * 4;
          
          lblXpE1.setText("Nivel: "+levelE1);
          lblXpE2.setText("Nivel: "+levelE2);
          lblXpE3.setText("Nivel: "+levelE3);
          
          lblText.setText("Las recomensas de mundo han sido aumentadas en un x"+worldLevel);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        lblWorld = new javax.swing.JLabel();
        lblSubtittle = new javax.swing.JLabel();
        cmbWorldLevel = new javax.swing.JComboBox<>();
        pnlSeparator2 = new javax.swing.JPanel();
        lblEnemy3 = new javax.swing.JLabel();
        lblEnemy1 = new javax.swing.JLabel();
        lblEnemy2 = new javax.swing.JLabel();
        lblXpE3 = new javax.swing.JLabel();
        lblXpE1 = new javax.swing.JLabel();
        lblXpE2 = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblTittle2 = new javax.swing.JLabel();
        lblTittle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        lblWorld.setText("jLabel1");
        jPanel1.add(lblWorld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 140));

        lblSubtittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtittle.setText("Nivel de mundo");
        jPanel1.add(lblSubtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 20));

        cmbWorldLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        cmbWorldLevel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbWorldLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWorldLevelItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbWorldLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 130, -1));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 59, 2, 380));

        lblEnemy3.setText("jLabel3");
        jPanel1.add(lblEnemy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 160, 210));

        lblEnemy1.setText("jLabel3");
        jPanel1.add(lblEnemy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, 210));

        lblEnemy2.setText("jLabel3");
        jPanel1.add(lblEnemy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 180, 210));

        lblXpE3.setText("Nivel");
        jPanel1.add(lblXpE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 140, -1));

        lblXpE1.setText("Nivel ");
        jPanel1.add(lblXpE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, -1));

        lblXpE2.setText("Nivel");
        jPanel1.add(lblXpE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 140, -1));

        lblText.setText("jLabel3");
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 520, 90));

        lblTittle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle2.setText("Observadores");
        jPanel1.add(lblTittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, -1));

        lblTittle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTittle1.setText("Observado");
        jPanel1.add(lblTittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void cmbWorldLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWorldLevelItemStateChanged
        calcularNivel(cmbWorldLevel.getSelectedIndex()+1);
    }//GEN-LAST:event_cmbWorldLevelItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Observer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Observer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Observer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Observer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Observer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JComboBox<String> cmbWorldLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnemy1;
    private javax.swing.JLabel lblEnemy2;
    private javax.swing.JLabel lblEnemy3;
    private javax.swing.JLabel lblSubtittle;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTittle1;
    private javax.swing.JLabel lblTittle2;
    private javax.swing.JLabel lblWorld;
    private javax.swing.JLabel lblXpE1;
    private javax.swing.JLabel lblXpE2;
    private javax.swing.JLabel lblXpE3;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
