/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Json.JsonInformation;
import java.awt.Color;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.json.simple.parser.ParseException;

public class PatternX extends javax.swing.JFrame {

    int mouseX, mouseY;
    JsonInformation info;
    Home newFrame;
    Color colorSelected;
    Color colorEntered;
    Color colorDefault;
    private String dato="";
    
    public PatternX() throws IOException, FileNotFoundException, ParseException {
        this.info = new JsonInformation();
        colorSelected = new Color(81,174,248);
        colorEntered = new Color(81,174,247);
        colorDefault = new Color(37, 133, 217);
        initComponents();
    }
    
    public void setDato(String dato){
        this.dato=dato;
        lblTitle.setText(dato);
        lblDefinition.setText("<html>" + info.getInfo(dato, "Definicion") + "<html>");
        btnDefinition.setBackground(colorSelected);
    }
    
    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void defaultButtons(){
        btnDefinition.setBackground(colorDefault);
        btnAdvantage.setBackground(colorDefault);
        btnImplement.setBackground(colorDefault);
        btnDiagram.setBackground(colorDefault);
        btnCodeExample.setBackground(colorDefault);
        btnExperience.setBackground(colorDefault);
        btnReferences.setBackground(colorDefault);
    }
    
    private void window(String nombre){
        
        switch(nombre){
            case "FactoryMethod":
                FactoryMethod newframe = new FactoryMethod();
                newframe.setVisible(true);
                break;
            case "AbstractFactory":
                AbstractFactory newframe1 = new AbstractFactory();
                newframe1.setVisible(true);
                break;
            case "Builder":
                Builder newframe2 = new Builder();
                newframe2.setVisible(true);
                break;
                
            case "Prototye":
                Prototype newframe3 = new Prototype();
                newframe3.setVisible(true);
                break;
                
            case "Singleton":
                Singleton newframe4 = new Singleton();
                newframe4.setVisible(true);
                break;   
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        LblHome = new javax.swing.JLabel();
        btnDefinition = new javax.swing.JPanel();
        LblDefinition = new javax.swing.JLabel();
        btnAdvantage = new javax.swing.JPanel();
        LblAdvantege = new javax.swing.JLabel();
        btnImplement = new javax.swing.JPanel();
        LblImplement = new javax.swing.JLabel();
        btnDiagram = new javax.swing.JPanel();
        LblDiagram = new javax.swing.JLabel();
        btnCodeExample = new javax.swing.JPanel();
        LblCodeExample = new javax.swing.JLabel();
        btnExperience = new javax.swing.JPanel();
        LblExperience = new javax.swing.JLabel();
        btnReferences = new javax.swing.JPanel();
        LblReferences = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTab = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pnlDefinition = new javax.swing.JPanel();
        lblDefinition = new javax.swing.JLabel();
        pnlAdventage = new javax.swing.JPanel();
        lblAdvantages = new javax.swing.JLabel();
        lblAdvantages1 = new javax.swing.JLabel();
        pnlImplment = new javax.swing.JPanel();
        lblImplement = new javax.swing.JLabel();
        pnlDiagram = new javax.swing.JPanel();
        lblDiagram = new javax.swing.JLabel();
        btnBack = new javax.swing.JPanel();
        lblNext1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JPanel();
        lblNext = new javax.swing.JLabel();
        pnlCodeExample = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JPanel();
        lblNext2 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JPanel();
        lblNext3 = new javax.swing.JLabel();
        pnlExperience = new javax.swing.JPanel();
        lblExperience = new javax.swing.JLabel();
        pnlReferences = new javax.swing.JPanel();
        lblReferences = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 3, 480));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 640, 3));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCloseLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtCerrar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 60));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 590, 60));

        btnHome.setBackground(new java.awt.Color(37, 133, 217));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Home_icon.png"))); // NOI18N
        LblHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(LblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(LblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        btnDefinition.setBackground(new java.awt.Color(37, 133, 217));
        btnDefinition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblDefinition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDefinition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Definition_Icon.png"))); // NOI18N
        LblDefinition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblDefinition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDefinitionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblDefinitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblDefinitionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDefinitionLayout = new javax.swing.GroupLayout(btnDefinition);
        btnDefinition.setLayout(btnDefinitionLayout);
        btnDefinitionLayout.setHorizontalGroup(
            btnDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDefinitionLayout.createSequentialGroup()
                .addComponent(LblDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnDefinitionLayout.setVerticalGroup(
            btnDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDefinitionLayout.createSequentialGroup()
                .addComponent(LblDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnDefinition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 60));

        btnAdvantage.setBackground(new java.awt.Color(37, 133, 217));
        btnAdvantage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAdvantege.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblAdvantege.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Advantages_Icon.png"))); // NOI18N
        LblAdvantege.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblAdvantege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblAdvantegeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblAdvantegeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblAdvantegeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAdvantageLayout = new javax.swing.GroupLayout(btnAdvantage);
        btnAdvantage.setLayout(btnAdvantageLayout);
        btnAdvantageLayout.setHorizontalGroup(
            btnAdvantageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdvantageLayout.createSequentialGroup()
                .addComponent(LblAdvantege, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAdvantageLayout.setVerticalGroup(
            btnAdvantageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdvantageLayout.createSequentialGroup()
                .addComponent(LblAdvantege, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnAdvantage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 60, 60));

        btnImplement.setBackground(new java.awt.Color(37, 133, 217));
        btnImplement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblImplement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImplement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Implement_Icon.png"))); // NOI18N
        LblImplement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblImplement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblImplementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblImplementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblImplementMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnImplementLayout = new javax.swing.GroupLayout(btnImplement);
        btnImplement.setLayout(btnImplementLayout);
        btnImplementLayout.setHorizontalGroup(
            btnImplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImplementLayout.createSequentialGroup()
                .addComponent(LblImplement, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnImplementLayout.setVerticalGroup(
            btnImplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImplementLayout.createSequentialGroup()
                .addComponent(LblImplement, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnImplement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 60, 60));

        btnDiagram.setBackground(new java.awt.Color(37, 133, 217));
        btnDiagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblDiagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDiagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Diagram_Icon.png"))); // NOI18N
        LblDiagram.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblDiagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDiagramMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblDiagramMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblDiagramMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDiagramLayout = new javax.swing.GroupLayout(btnDiagram);
        btnDiagram.setLayout(btnDiagramLayout);
        btnDiagramLayout.setHorizontalGroup(
            btnDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDiagramLayout.createSequentialGroup()
                .addComponent(LblDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnDiagramLayout.setVerticalGroup(
            btnDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDiagramLayout.createSequentialGroup()
                .addComponent(LblDiagram, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnDiagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, 60));

        btnCodeExample.setBackground(new java.awt.Color(37, 133, 217));
        btnCodeExample.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblCodeExample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCodeExample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/CodeExample_Icon.png"))); // NOI18N
        LblCodeExample.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblCodeExample.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCodeExampleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblCodeExampleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblCodeExampleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCodeExampleLayout = new javax.swing.GroupLayout(btnCodeExample);
        btnCodeExample.setLayout(btnCodeExampleLayout);
        btnCodeExampleLayout.setHorizontalGroup(
            btnCodeExampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCodeExampleLayout.createSequentialGroup()
                .addComponent(LblCodeExample, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCodeExampleLayout.setVerticalGroup(
            btnCodeExampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCodeExampleLayout.createSequentialGroup()
                .addComponent(LblCodeExample, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnCodeExample, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 60, 60));

        btnExperience.setBackground(new java.awt.Color(37, 133, 217));
        btnExperience.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblExperience.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblExperience.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/Experience_Icon.png"))); // NOI18N
        LblExperience.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblExperience.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblExperienceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblExperienceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblExperienceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExperienceLayout = new javax.swing.GroupLayout(btnExperience);
        btnExperience.setLayout(btnExperienceLayout);
        btnExperienceLayout.setHorizontalGroup(
            btnExperienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExperienceLayout.createSequentialGroup()
                .addComponent(LblExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnExperienceLayout.setVerticalGroup(
            btnExperienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExperienceLayout.createSequentialGroup()
                .addComponent(LblExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 60, 60));

        btnReferences.setBackground(new java.awt.Color(37, 133, 217));
        btnReferences.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblReferences.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblReferences.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/IMG/Icons/Patterns/References_Icon.png"))); // NOI18N
        LblReferences.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblReferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblReferencesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LblReferencesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LblReferencesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnReferencesLayout = new javax.swing.GroupLayout(btnReferences);
        btnReferences.setLayout(btnReferencesLayout);
        btnReferencesLayout.setHorizontalGroup(
            btnReferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReferencesLayout.createSequentialGroup()
                .addComponent(LblReferences, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnReferencesLayout.setVerticalGroup(
            btnReferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReferencesLayout.createSequentialGroup()
                .addComponent(LblReferences, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnReferences, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 60, 60));

        lblTitle.setFont(new java.awt.Font("Instrument Sans", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<html>texto ejemplo<html>");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 430, 60));

        lblTab.setBackground(new java.awt.Color(255, 255, 255));
        lblTab.setFont(new java.awt.Font("Instrument Sans", 1, 12)); // NOI18N
        lblTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTab.setText("<html>Definición<html>");
        jPanel1.add(lblTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 540, 30));

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        pnlDefinition.setBackground(new java.awt.Color(255, 255, 255));

        lblDefinition.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDefinition.setText("Text");
        lblDefinition.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlDefinitionLayout = new javax.swing.GroupLayout(pnlDefinition);
        pnlDefinition.setLayout(pnlDefinitionLayout);
        pnlDefinitionLayout.setHorizontalGroup(
            pnlDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDefinitionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlDefinitionLayout.setVerticalGroup(
            pnlDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDefinition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("", pnlDefinition);

        pnlAdventage.setBackground(new java.awt.Color(255, 255, 255));

        lblAdvantages.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdvantages.setText("Text");
        lblAdvantages.setToolTipText("");
        lblAdvantages.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblAdvantages1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdvantages1.setText("Text");
        lblAdvantages1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlAdventageLayout = new javax.swing.GroupLayout(pnlAdventage);
        pnlAdventage.setLayout(pnlAdventageLayout);
        pnlAdventageLayout.setHorizontalGroup(
            pnlAdventageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdventageLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblAdvantages, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdvantages1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAdventageLayout.setVerticalGroup(
            pnlAdventageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdventageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdventageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdvantages, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdvantages1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("", pnlAdventage);

        pnlImplment.setBackground(new java.awt.Color(255, 255, 255));

        lblImplement.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblImplement.setText("Text");
        lblImplement.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlImplmentLayout = new javax.swing.GroupLayout(pnlImplment);
        pnlImplment.setLayout(pnlImplmentLayout);
        pnlImplmentLayout.setHorizontalGroup(
            pnlImplmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImplmentLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(lblImplement, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlImplmentLayout.setVerticalGroup(
            pnlImplmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImplmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImplement, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("", pnlImplment);

        pnlDiagram.setBackground(new java.awt.Color(255, 255, 255));

        lblNext1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext1.setText("<");
        lblNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNext1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNext1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNext1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBackLayout = new javax.swing.GroupLayout(btnBack);
        btnBack.setLayout(btnBackLayout);
        btnBackLayout.setHorizontalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnBackLayout.setVerticalGroup(
            btnBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
        );

        lblNext.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setText(">");
        lblNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNextLayout = new javax.swing.GroupLayout(btnNext);
        btnNext.setLayout(btnNextLayout);
        btnNextLayout.setHorizontalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnNextLayout.setVerticalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDiagramLayout = new javax.swing.GroupLayout(pnlDiagram);
        pnlDiagram.setLayout(pnlDiagramLayout);
        pnlDiagramLayout.setHorizontalGroup(
            pnlDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiagramLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiagram, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlDiagramLayout.setVerticalGroup(
            pnlDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiagramLayout.createSequentialGroup()
                .addGroup(pnlDiagramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiagram, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(pnlDiagramLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlDiagramLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("", pnlDiagram);

        pnlCodeExample.setBackground(new java.awt.Color(255, 255, 255));

        lblNext2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNext2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext2.setText("<");
        lblNext2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNext2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNext2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNext2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBack1Layout = new javax.swing.GroupLayout(btnBack1);
        btnBack1.setLayout(btnBack1Layout);
        btnBack1Layout.setHorizontalGroup(
            btnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnBack1Layout.setVerticalGroup(
            btnBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
        );

        lblNext3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNext3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext3.setText(">");
        lblNext3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNext3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNext3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNext3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNext3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnNext1Layout = new javax.swing.GroupLayout(btnNext1);
        btnNext1.setLayout(btnNext1Layout);
        btnNext1Layout.setHorizontalGroup(
            btnNext1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnNext1Layout.setVerticalGroup(
            btnNext1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNext3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCodeExampleLayout = new javax.swing.GroupLayout(pnlCodeExample);
        pnlCodeExample.setLayout(pnlCodeExampleLayout);
        pnlCodeExampleLayout.setHorizontalGroup(
            pnlCodeExampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCodeExampleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCodeExampleLayout.setVerticalGroup(
            pnlCodeExampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodeExampleLayout.createSequentialGroup()
                .addGroup(pnlCodeExampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(pnlCodeExampleLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlCodeExampleLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("", pnlCodeExample);

        pnlExperience.setBackground(new java.awt.Color(255, 255, 255));

        lblExperience.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblExperience.setText("Text");
        lblExperience.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlExperienceLayout = new javax.swing.GroupLayout(pnlExperience);
        pnlExperience.setLayout(pnlExperienceLayout);
        pnlExperienceLayout.setHorizontalGroup(
            pnlExperienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExperienceLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExperienceLayout.setVerticalGroup(
            pnlExperienceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExperienceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("", pnlExperience);

        pnlReferences.setBackground(new java.awt.Color(255, 255, 255));

        lblReferences.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblReferences.setText("Text");
        lblReferences.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlReferencesLayout = new javax.swing.GroupLayout(pnlReferences);
        pnlReferences.setLayout(pnlReferencesLayout);
        pnlReferencesLayout.setHorizontalGroup(
            pnlReferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferencesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblReferences, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlReferencesLayout.setVerticalGroup(
            pnlReferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReferencesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblReferences, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("", pnlReferences);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 660, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void LblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHomeMouseClicked
        try {
            newFrame = new Home();
        } catch (IOException ex) {
            Logger.getLogger(PatternX.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(PatternX.class.getName()).log(Level.SEVERE, null, ex);
        }
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblHomeMouseClicked

    private void LblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHomeMouseEntered
        btnHome.setOpaque(true);
        btnHome.setBackground(colorEntered);
    }//GEN-LAST:event_LblHomeMouseEntered

    private void LblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblHomeMouseExited
        btnHome.setOpaque(true);
        btnHome.setBackground(colorDefault);
    }//GEN-LAST:event_LblHomeMouseExited

    private void LblDefinitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDefinitionMouseEntered
        if (btnDefinition.getBackground().equals(colorDefault)) {
            btnDefinition.setOpaque(true);
            btnDefinition.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblDefinitionMouseEntered

    private void LblDefinitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDefinitionMouseExited
        if (btnDefinition.getBackground().equals(colorEntered)) {
            btnDefinition.setOpaque(true);
            btnDefinition.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblDefinitionMouseExited

    private void LblAdvantegeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdvantegeMouseEntered
        if(btnAdvantage.getBackground().equals(colorDefault)){
            btnAdvantage.setOpaque(true);
            btnAdvantage.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblAdvantegeMouseEntered

    private void LblAdvantegeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdvantegeMouseExited
        if(btnAdvantage.getBackground().equals(colorEntered)){
            btnAdvantage.setOpaque(true);
            btnAdvantage.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblAdvantegeMouseExited

    private void LblImplementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblImplementMouseEntered
        if (btnImplement.getBackground().equals(colorDefault)) {
            btnImplement.setOpaque(true);
            btnImplement.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblImplementMouseEntered

    private void LblImplementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblImplementMouseExited
        if (btnImplement.getBackground().equals(colorEntered)) {
            btnImplement.setOpaque(true);
            btnImplement.setBackground(colorDefault);   
        }
    }//GEN-LAST:event_LblImplementMouseExited

    private void LblDiagramMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDiagramMouseEntered
        if(btnDiagram.getBackground().equals(colorDefault)){
            btnDiagram.setOpaque(true);
            btnDiagram.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblDiagramMouseEntered

    private void LblDiagramMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDiagramMouseExited
        if(btnDiagram.getBackground().equals(colorEntered)){
            btnDiagram.setOpaque(true);
            btnDiagram.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblDiagramMouseExited

    private void LblCodeExampleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCodeExampleMouseEntered
        if (btnCodeExample.getBackground().equals(colorDefault)) {
            btnCodeExample.setOpaque(true);
            btnCodeExample.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblCodeExampleMouseEntered

    private void LblCodeExampleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCodeExampleMouseExited
        if (btnCodeExample.getBackground().equals(colorEntered)) {
            btnCodeExample.setOpaque(true);
            btnCodeExample.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblCodeExampleMouseExited

    private void LblExperienceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExperienceMouseEntered
        if (btnExperience.getBackground().equals(colorDefault)) {
            btnExperience.setOpaque(true);
            btnExperience.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblExperienceMouseEntered

    private void LblExperienceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExperienceMouseExited
        if (btnExperience.getBackground().equals(colorEntered)) {
            btnExperience.setOpaque(true);
            btnExperience.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblExperienceMouseExited

    private void LblReferencesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblReferencesMouseEntered
        if (btnReferences.getBackground().equals(colorDefault)) {
            btnReferences.setOpaque(true);
            btnReferences.setBackground(colorEntered);
        }
    }//GEN-LAST:event_LblReferencesMouseEntered

    private void LblReferencesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblReferencesMouseExited
        if (btnReferences.getBackground().equals(colorEntered)) {
            btnReferences.setOpaque(true);
            btnReferences.setBackground(colorDefault);
        }
    }//GEN-LAST:event_LblReferencesMouseExited

    private void LblDefinitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDefinitionMouseClicked
        tabs.setSelectedIndex(0);
        lblTab.setText("Definición");
        defaultButtons();
        btnDefinition.setBackground(colorSelected);
        lblDefinition.setText("<html>" + info.getInfo(dato, "Definicion") + "<html>");
    }//GEN-LAST:event_LblDefinitionMouseClicked

    private void LblAdvantegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblAdvantegeMouseClicked
        tabs.setSelectedIndex(1);
        lblTab.setText("Ventajas y Desventajas");
        defaultButtons();
        btnAdvantage.setBackground(colorSelected);
        lblAdvantages.setText("<html>"+info.getList(dato, "Ventajas")+"<html>");
        lblAdvantages1.setText("<html>"+info.getList(dato, "Desventajas")+"<html>");
    }//GEN-LAST:event_LblAdvantegeMouseClicked

    private void LblImplementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblImplementMouseClicked
        tabs.setSelectedIndex(2);
        lblTab.setText("Pasos de Implementación");
        defaultButtons();
        btnImplement.setBackground(colorSelected);
        lblImplement.setText("<html>"+info.getList(dato, "Implementacion")+"<html>");
        
    }//GEN-LAST:event_LblImplementMouseClicked

    private void LblDiagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDiagramMouseClicked
        tabs.setSelectedIndex(3);
        lblTab.setText("Ejemplo con Diagrama de Clases");
        defaultButtons();
        btnDiagram.setBackground(colorSelected);
        setImageLabel(lblDiagram, "src/Assets/IMG//Diagramas//DiagramaUML_"+dato+".png");
        
        
    }//GEN-LAST:event_LblDiagramMouseClicked

    private void LblCodeExampleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCodeExampleMouseClicked
        tabs.setSelectedIndex(4);
        lblTab.setText("Ejemplo en Código");
        defaultButtons();
        btnCodeExample.setBackground(colorSelected);
        
    }//GEN-LAST:event_LblCodeExampleMouseClicked

    private void LblExperienceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblExperienceMouseClicked
        tabs.setSelectedIndex(5);
        lblTab.setText("Experiencia Interactiva");
        defaultButtons();
        btnExperience.setBackground(colorSelected);
        window(dato);
    }//GEN-LAST:event_LblExperienceMouseClicked

    private void LblReferencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblReferencesMouseClicked
        tabs.setSelectedIndex(6);
        lblTab.setText("Referencias");
        defaultButtons();
        btnReferences.setBackground(colorSelected);
        lblReferences.setText("<html>"+info.getList(dato, "Referencias")+"<html>");
    }//GEN-LAST:event_LblReferencesMouseClicked

    private void lblNext1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseEntered
        btnBack.setOpaque(true);
        btnBack.setBackground(Color.gray);
    }//GEN-LAST:event_lblNext1MouseEntered

    private void lblNext1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseExited
        btnBack.setOpaque(true);
        btnBack.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_lblNext1MouseExited

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        setImageLabel(lblDiagram, "src/Assets/IMG//Diagramas//DiagramaUML_"+dato+"Ex.png");   
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseEntered
        btnNext.setOpaque(true);
        btnNext.setBackground(Color.gray);
    }//GEN-LAST:event_lblNextMouseEntered

    private void lblNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseExited
        btnNext.setOpaque(true);
        btnNext.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_lblNextMouseExited

    private void lblNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext1MouseClicked
        setImageLabel(lblDiagram, "src/Assets/IMG//Diagramas//DiagramaUML_"+dato+".png");
    }//GEN-LAST:event_lblNext1MouseClicked

    private void lblNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext2MouseClicked

    private void lblNext2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext2MouseEntered

    private void lblNext2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext2MouseExited

    private void lblNext3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext3MouseClicked

    private void lblNext3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext3MouseEntered

    private void lblNext3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNext3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNext3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatternX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatternX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatternX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatternX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PatternX().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PatternX.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(PatternX.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LblAdvantege;
    private javax.swing.JLabel LblCodeExample;
    private javax.swing.JLabel LblDefinition;
    private javax.swing.JLabel LblDiagram;
    private javax.swing.JLabel LblExperience;
    private javax.swing.JLabel LblHome;
    private javax.swing.JLabel LblImplement;
    private javax.swing.JLabel LblReferences;
    private javax.swing.JPanel btnAdvantage;
    private javax.swing.JPanel btnBack;
    private javax.swing.JPanel btnBack1;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnCodeExample;
    private javax.swing.JPanel btnDefinition;
    private javax.swing.JPanel btnDiagram;
    private javax.swing.JPanel btnExperience;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnImplement;
    private javax.swing.JPanel btnNext;
    private javax.swing.JPanel btnNext1;
    private javax.swing.JPanel btnReferences;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdvantages;
    private javax.swing.JLabel lblAdvantages1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDefinition;
    private javax.swing.JLabel lblDiagram;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblImplement;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblNext1;
    private javax.swing.JLabel lblNext2;
    private javax.swing.JLabel lblNext3;
    private javax.swing.JLabel lblReferences;
    private javax.swing.JLabel lblTab;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAdventage;
    private javax.swing.JPanel pnlCodeExample;
    private javax.swing.JPanel pnlDefinition;
    private javax.swing.JPanel pnlDiagram;
    private javax.swing.JPanel pnlExperience;
    private javax.swing.JPanel pnlImplment;
    private javax.swing.JPanel pnlReferences;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
