/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Singleton extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    
    public Singleton() {
        initComponents();
        decorator();
        setImageLabel(lblTree,"src/Assets/IMG/Singleton/Tree1.png");
        btnEnemy.setOpaque(false);
        btnTree.setOpaque(false);
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        
        lblSpawn.setFont(typeFont.fontV(typeFont.instruments, 0, 18));
        lblMemory.setFont(typeFont.fontV(typeFont.instruments, 0, 18));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        btnTree = new javax.swing.JPanel();
        btnEnemy = new javax.swing.JPanel();
        lblTree = new javax.swing.JLabel();
        btnSpawn = new javax.swing.JPanel();
        lblSpawn = new javax.swing.JLabel();
        lblEnemy = new javax.swing.JLabel();
        lblArrow = new javax.swing.JLabel();
        lblMemory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        btnTree.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnTreeLayout = new javax.swing.GroupLayout(btnTree);
        btnTree.setLayout(btnTreeLayout);
        btnTreeLayout.setHorizontalGroup(
            btnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        btnTreeLayout.setVerticalGroup(
            btnTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(btnTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 230, 70, 70));

        btnEnemy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnemy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnemyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEnemyLayout = new javax.swing.GroupLayout(btnEnemy);
        btnEnemy.setLayout(btnEnemyLayout);
        btnEnemyLayout.setHorizontalGroup(
            btnEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnEnemyLayout.setVerticalGroup(
            btnEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(btnEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        lblTree.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jPanel1.add(lblTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 340, 300));

        btnSpawn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSpawn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpawn.setText("Spawn Creaking");
        lblSpawn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpawnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSpawnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSpawnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSpawnLayout = new javax.swing.GroupLayout(btnSpawn);
        btnSpawn.setLayout(btnSpawnLayout);
        btnSpawnLayout.setHorizontalGroup(
            btnSpawnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpawn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnSpawnLayout.setVerticalGroup(
            btnSpawnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpawn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnSpawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 50));

        lblEnemy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 240));
        jPanel1.add(lblArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, 70));
        jPanel1.add(lblMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblSpawnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpawnMouseEntered
        btnSpawn.setOpaque(true);
        btnSpawn.setBackground(Color.gray);
    }//GEN-LAST:event_lblSpawnMouseEntered

    private void lblSpawnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpawnMouseExited
        btnSpawn.setOpaque(true);
        btnSpawn.setBackground(new Color(214, 217, 223));
    }//GEN-LAST:event_lblSpawnMouseExited

    private void lblSpawnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpawnMouseClicked
        if(lblEnemy.getIcon()==null){
            setImageLabel(lblEnemy, "src/Assets/IMG/Singleton/Creaking.png");
            Object memory = new Object();
            lblMemory.setText("Dirección en memoria: "+Integer.toHexString(System.identityHashCode(memory)));
        }else{
            JOptionPane.showMessageDialog(null, "Solo se puede generar un Creaking por corazon!!");
        
        }
        
        
        
    }//GEN-LAST:event_lblSpawnMouseClicked

    private void btnEnemyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnemyMouseClicked
        if(lblEnemy.getIcon()!=null){
            setImageLabel(lblArrow,"src/Assets/IMG/Singleton/Arrow.png");
            setImageLabel(lblTree,"src/Assets/IMG/Singleton/TreeWithLight1.png");
            lblTree.setText("Light");
        }
        
        
        
    }//GEN-LAST:event_btnEnemyMouseClicked

    private void btnTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreeMouseClicked
        if(lblTree.getText().equals("Light")){
            lblEnemy.setIcon(null);
            lblArrow.setIcon(null);
            setImageLabel(lblTree,"src/Assets/IMG/Singleton/Tree1.png");
            lblMemory.setText("");
            JOptionPane.showMessageDialog(null, "Matas al Creaking rompiendo su corazon");
        }
    }//GEN-LAST:event_btnTreeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Singleton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Singleton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Singleton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Singleton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Singleton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnEnemy;
    private javax.swing.JPanel btnSpawn;
    private javax.swing.JPanel btnTree;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArrow;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JLabel lblSpawn;
    private javax.swing.JLabel lblTree;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
