/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class State extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    String state="tr";
    
    public State() {
        
        initComponents();
        decorator();
        
    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        setImageLabel(lblSaurio1,"src/Assets/IMG/State/saurio1_Icon.png");
        setImageLabel(lblSaurio2,"src/Assets/IMG/State/saurio2_Icon.png");
        setImageLabel(lblSaurio3,"src/Assets/IMG/State/saurio3_Icon.png");
        setImageLabel(lblReset,"src/Assets/IMG/State/reset_Icon.png");
        setImageLabel(lblSaurio,"src/Assets/IMG/State/viajero_Img.png");
        
        setImageLabel(lblHabilitty1,"src/Assets/IMG/State/attack_Icon.png");
        setImageLabel(lblHabilitty2,"src/Assets/IMG/State/magic_Icon.png");
        setImageLabel(lblHabilitty3,"src/Assets/IMG/State/run_Icon.png");
        
        lblText.setFont(typeFont.fontV(typeFont.instruments, 0, 18));
        pnlContainer.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        btnSaurio1 = new javax.swing.JPanel();
        lblSaurio1 = new javax.swing.JLabel();
        btnSaurio2 = new javax.swing.JPanel();
        lblSaurio2 = new javax.swing.JLabel();
        btnSaurio3 = new javax.swing.JPanel();
        lblSaurio3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        lblReset = new javax.swing.JLabel();
        pnlSeparator2 = new javax.swing.JPanel();
        lblSaurio = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        btnHability1 = new javax.swing.JPanel();
        lblHabilitty1 = new javax.swing.JLabel();
        btnHability2 = new javax.swing.JPanel();
        lblHabilitty2 = new javax.swing.JLabel();
        btnHability3 = new javax.swing.JPanel();
        lblHabilitty3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        lblSaurio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaurio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaurio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaurio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaurio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaurio1MouseExited(evt);
            }
        });
        lblSaurio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblSaurio1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout btnSaurio1Layout = new javax.swing.GroupLayout(btnSaurio1);
        btnSaurio1.setLayout(btnSaurio1Layout);
        btnSaurio1Layout.setHorizontalGroup(
            btnSaurio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnSaurio1Layout.setVerticalGroup(
            btnSaurio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnSaurio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        lblSaurio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaurio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaurio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaurio2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaurio2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaurio2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSaurio2Layout = new javax.swing.GroupLayout(btnSaurio2);
        btnSaurio2.setLayout(btnSaurio2Layout);
        btnSaurio2Layout.setHorizontalGroup(
            btnSaurio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnSaurio2Layout.setVerticalGroup(
            btnSaurio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnSaurio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblSaurio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaurio3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaurio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaurio3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaurio3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaurio3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSaurio3Layout = new javax.swing.GroupLayout(btnSaurio3);
        btnSaurio3.setLayout(btnSaurio3Layout);
        btnSaurio3Layout.setHorizontalGroup(
            btnSaurio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnSaurio3Layout.setVerticalGroup(
            btnSaurio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaurio3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnSaurio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReset, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 59, 2, 380));
        jPanel1.add(lblSaurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 260, 320));

        lblText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTextMouseEntered(evt);
            }
        });
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 310, 190));

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zona de habilidades", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblHabilitty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHabilitty1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHabilitty1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHabilitty1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHabilitty1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHabilitty1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHability1Layout = new javax.swing.GroupLayout(btnHability1);
        btnHability1.setLayout(btnHability1Layout);
        btnHability1Layout.setHorizontalGroup(
            btnHability1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnHability1Layout.setVerticalGroup(
            btnHability1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lblHabilitty2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHabilitty2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHabilitty2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHabilitty2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHabilitty2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHabilitty2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHability2Layout = new javax.swing.GroupLayout(btnHability2);
        btnHability2.setLayout(btnHability2Layout);
        btnHability2Layout.setHorizontalGroup(
            btnHability2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnHability2Layout.setVerticalGroup(
            btnHability2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        lblHabilitty3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHabilitty3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHabilitty3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHabilitty3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHabilitty3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHabilitty3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHability3Layout = new javax.swing.GroupLayout(btnHability3);
        btnHability3.setLayout(btnHability3Layout);
        btnHability3Layout.setHorizontalGroup(
            btnHability3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnHability3Layout.setVerticalGroup(
            btnHability3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHabilitty3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnHability1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHability2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHability3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHability3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHability2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHability1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 350, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblSaurio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio1MouseEntered
        btnSaurio1.setOpaque(true);
        btnSaurio1.setBackground(colorEntered);
    }//GEN-LAST:event_lblSaurio1MouseEntered

    private void lblSaurio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio1MouseExited
        btnSaurio1.setOpaque(true);
        btnSaurio1.setBackground(colorDefault);
    }//GEN-LAST:event_lblSaurio1MouseExited

    private void lblSaurio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio2MouseEntered
        btnSaurio2.setOpaque(true);
        btnSaurio2.setBackground(colorEntered);
    }//GEN-LAST:event_lblSaurio2MouseEntered

    private void lblSaurio2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio2MouseExited
        btnSaurio2.setOpaque(true);
        btnSaurio2.setBackground(colorDefault);
    }//GEN-LAST:event_lblSaurio2MouseExited

    private void lblSaurio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio3MouseEntered
        btnSaurio3.setOpaque(true);
        btnSaurio3.setBackground(colorEntered);
    }//GEN-LAST:event_lblSaurio3MouseEntered

    private void lblSaurio3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio3MouseExited
        btnSaurio3.setOpaque(true);
        btnSaurio3.setBackground(colorDefault);
    }//GEN-LAST:event_lblSaurio3MouseExited

    private void lblResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseEntered
        btnReset.setOpaque(true);
        btnReset.setBackground(colorEntered);
    }//GEN-LAST:event_lblResetMouseEntered

    private void lblResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseExited
        btnReset.setOpaque(true);
        btnReset.setBackground(colorDefault);
    }//GEN-LAST:event_lblResetMouseExited

    private void lblSaurio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio1MouseClicked
        setImageLabel(lblSaurio,"src/Assets/IMG/State/saurio1_Img.png");
        state="s1";
        lblText.setText("");
    }//GEN-LAST:event_lblSaurio1MouseClicked

    private void lblSaurio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio2MouseClicked
        setImageLabel(lblSaurio,"src/Assets/IMG/State/saurio2_Img.png");
        state="s2";
        lblText.setText("");
    }//GEN-LAST:event_lblSaurio2MouseClicked

    private void lblSaurio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaurio3MouseClicked
        setImageLabel(lblSaurio,"src/Assets/IMG/State/saurio3_Img.png");
        state="s3";
        lblText.setText("");
    }//GEN-LAST:event_lblSaurio3MouseClicked

    private void lblSaurio1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblSaurio1KeyPressed

    }//GEN-LAST:event_lblSaurio1KeyPressed

    private void lblTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextMouseEntered

    }//GEN-LAST:event_lblTextMouseEntered

    private void lblHabilitty1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty1MouseClicked
        switch (state){
            case "s1":
                lblText.setText("<html>Yumkasaurio ataca al enemigo con sus afiladas garras<html>");
                
                break;
                
            case "s2":
                lblText.setText("<html>Koholasaurio  muerde con sus afilados dientes al enemigo<html>");
                
                break;
            
            case "s3":
                lblText.setText("<html>Tepetlisaurio arremete con su fuerte cuerno al enemigo<html>");
                
                break;
                
            case "tr":
                lblText.setText("<html>El viajero blande su espada con firmeza para atacar al enemigo<html>");
                
                break;
        
        }
    }//GEN-LAST:event_lblHabilitty1MouseClicked

    private void lblHabilitty1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty1MouseEntered
        btnHability1.setOpaque(true);
        btnHability1.setBackground(colorEntered);
    }//GEN-LAST:event_lblHabilitty1MouseEntered

    private void lblHabilitty1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty1MouseExited
        btnHability1.setOpaque(true);
        btnHability1.setBackground(colorDefault);
    }//GEN-LAST:event_lblHabilitty1MouseExited

    private void lblHabilitty2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty2MouseClicked
        switch (state){
            case "s1":
                lblText.setText("<html>Yumkasaurio escupe una bola de fuego al enemigo<html>");
                
                break;
                
            case "s2":
                lblText.setText("<html>Koholasaurio gira a toda velocidad envolviendose en agua para perforar al enemigo<html>");
                
                break;
            
            case "s3":
                lblText.setText("<html>Tepetlisaurio se imbuye en rocas y arremete con todo su cuerpo al enemigo<html>");
                
                break;
                
            case "tr":
                lblText.setText("<html>El viajero utiliza la sinergia con los elementos para crear un tornado de sus manos <html>");
                
                break;
        
        }
        
    }//GEN-LAST:event_lblHabilitty2MouseClicked

    private void lblHabilitty2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty2MouseEntered
        btnHability2.setOpaque(true);
        btnHability2.setBackground(colorEntered);
    }//GEN-LAST:event_lblHabilitty2MouseEntered

    private void lblHabilitty2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty2MouseExited
        btnHability2.setOpaque(true);
        btnHability2.setBackground(colorDefault);
    }//GEN-LAST:event_lblHabilitty2MouseExited

    private void lblHabilitty3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty3MouseClicked
            switch (state){
            case "s1":
                lblText.setText("<html>Yumkasaurio utiliza su lengua para columpiarse entre los arboles aumentando su velocidad<html>");
                
                break;
                
            case "s2":
                lblText.setText("<html>Koholasaurio se sumerge bajo el agua y aumenta su velocidad<html>");
                
                break;
            
            case "s3":
                lblText.setText("<html>Tepetlisaurio se esconde bajo tierra y empieza excavar a gran velocidad<html>");
                
                break;
                
            case "tr":
                lblText.setText("<html>El viajero empieza a correr a su maxima velocidad <html>");
                
                break;
        
        }
 
        
    }//GEN-LAST:event_lblHabilitty3MouseClicked

    private void lblHabilitty3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty3MouseEntered
        btnHability3.setOpaque(true);
        btnHability3.setBackground(colorEntered);
    }//GEN-LAST:event_lblHabilitty3MouseEntered

    private void lblHabilitty3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHabilitty3MouseExited
        btnHability3.setOpaque(true);
        btnHability3.setBackground(colorDefault);
    }//GEN-LAST:event_lblHabilitty3MouseExited

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        setImageLabel(lblSaurio,"src/Assets/IMG/State/viajero_Img.png");
        state="tr";
        lblText.setText("");
    }//GEN-LAST:event_lblResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(State.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(State.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(State.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(State.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new State().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnHability1;
    private javax.swing.JPanel btnHability2;
    private javax.swing.JPanel btnHability3;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnSaurio1;
    private javax.swing.JPanel btnSaurio2;
    private javax.swing.JPanel btnSaurio3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHabilitty1;
    private javax.swing.JLabel lblHabilitty2;
    private javax.swing.JLabel lblHabilitty3;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblSaurio;
    private javax.swing.JLabel lblSaurio1;
    private javax.swing.JLabel lblSaurio2;
    private javax.swing.JLabel lblSaurio3;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
