/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Strategy extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
   
    String value="";
    
    public Strategy() {
        initComponents();
        decorator();

    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }

    
    
    private void decorator(){
        typeFont = new Fonts();
        setImageLabel(lblAnemo, "src\\Assets\\IMG\\Strategy\\anemo_Icon.png");
        setImageLabel(lblGeo, "src\\Assets\\IMG\\Strategy\\geo_Icon.png");
        setImageLabel(lblElectro, "src\\Assets\\IMG\\Strategy\\electro_Icon.png");
        setImageLabel(lblDendro, "src\\Assets\\IMG\\Strategy\\dendro_Icon.png");
        setImageLabel(lblHydro, "src\\Assets\\IMG\\Strategy\\hydro_Icon.png");
        setImageLabel(lblHydro, "src\\Assets\\IMG\\Strategy\\hydro_Icon.png");
        setImageLabel(lblElemental, "src\\Assets\\IMG\\Strategy\\Attack_Icon.png");
        setImageLabel(lblUltimate, "src\\Assets\\IMG\\Strategy\\magic_Icon.png");
        
        lblSubtittle.setFont(typeFont.fontV(typeFont.instruments, 1, 12));
        lblText.setFont(typeFont.fontV(typeFont.instruments, 0, 12));
        
    }
    
    private void setTxt(String type){
        switch(this.value){
            case "A":
                
                if(type.equals("elemental")){
                    lblText.setText("<html>El viajero convoca los viento usando sus manos para crear un remolino<html>");
                }else if(type.equals("ultimate")){
                    lblText.setText("<html>El viajero convoca los viento usando sus espada para crear un tornado<html>");
                }
                
                break;
           
            case "D":
                if(type.equals("elemental")){
                    lblText.setText("<html>El viajero utiliza su espada invcando el poder de las flores para atacar<html>");
                }else if(type.equals("ultimate")){
                    lblText.setText("<html>El viajero utiliza el poder de las flores para generar un campo de explosiones<html>");
                }
                break;
                
            case "E":
                if(type.equals("elemental")){
                    lblText.setText("<html>El viajero lanza 3 rayos desde su espada<html>");
                }else if(type.equals("ultimate")){
                    lblText.setText("<html>El viajero convoca con sus manos un rayo<html>");
                }
                break;
                
            case "G":
                if(type.equals("elemental")){
                    lblText.setText("<html>El viajero convoca una piedra para protegerse<html>");
                }else if(type.equals("ultimate")){
                    lblText.setText("<html>El viajero provoca con sus puños un fuerte temblor<html>");
                }
                break;
                
            case "H":
                if(type.equals("elemental")){
                    lblText.setText("<html>El viajero apunta con sus manos y dispara gotas de agua envenendada<html>");
                }else if(type.equals("ultimate")){
                    lblText.setText("<html>El viajero convoca una esfera de agua que absorbe a los enemigos<html>");
                }
                
                break;
        
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        lblPj = new javax.swing.JLabel();
        btnAnemo = new javax.swing.JPanel();
        lblAnemo = new javax.swing.JLabel();
        btnElectro = new javax.swing.JPanel();
        lblElectro = new javax.swing.JLabel();
        btnDendro = new javax.swing.JPanel();
        lblDendro = new javax.swing.JLabel();
        btnHydro = new javax.swing.JPanel();
        lblHydro = new javax.swing.JLabel();
        btnGeo = new javax.swing.JPanel();
        lblGeo = new javax.swing.JLabel();
        pnlSeparator2 = new javax.swing.JPanel();
        btnElemental = new javax.swing.JPanel();
        lblElemental = new javax.swing.JLabel();
        btnUltimate = new javax.swing.JPanel();
        lblUltimate = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblSubtittle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));
        jPanel1.add(lblPj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 280, 270));

        btnAnemo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAnemo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnemoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAnemoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAnemoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAnemoLayout = new javax.swing.GroupLayout(btnAnemo);
        btnAnemo.setLayout(btnAnemoLayout);
        btnAnemoLayout.setHorizontalGroup(
            btnAnemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnemo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnAnemoLayout.setVerticalGroup(
            btnAnemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnemo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAnemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 60, 60));

        btnElectro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblElectro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElectroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElectroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblElectroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnElectroLayout = new javax.swing.GroupLayout(btnElectro);
        btnElectro.setLayout(btnElectroLayout);
        btnElectroLayout.setHorizontalGroup(
            btnElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElectro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnElectroLayout.setVerticalGroup(
            btnElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElectro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnElectro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 60, 60));

        btnDendro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDendro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDendroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDendroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDendroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDendroLayout = new javax.swing.GroupLayout(btnDendro);
        btnDendro.setLayout(btnDendroLayout);
        btnDendroLayout.setHorizontalGroup(
            btnDendroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDendro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnDendroLayout.setVerticalGroup(
            btnDendroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDendro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnDendro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 60, 60));

        btnHydro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblHydro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHydroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHydroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHydroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHydroLayout = new javax.swing.GroupLayout(btnHydro);
        btnHydro.setLayout(btnHydroLayout);
        btnHydroLayout.setHorizontalGroup(
            btnHydroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHydro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnHydroLayout.setVerticalGroup(
            btnHydroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHydro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnHydro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 60, 60));

        btnGeo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGeoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGeoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGeoLayout = new javax.swing.GroupLayout(btnGeo);
        btnGeo.setLayout(btnGeoLayout);
        btnGeoLayout.setHorizontalGroup(
            btnGeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGeo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        btnGeoLayout.setVerticalGroup(
            btnGeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGeo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 60, 60));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 59, 2, 380));

        lblElemental.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblElemental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElementalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElementalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblElementalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnElementalLayout = new javax.swing.GroupLayout(btnElemental);
        btnElemental.setLayout(btnElementalLayout);
        btnElementalLayout.setHorizontalGroup(
            btnElementalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElemental, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnElementalLayout.setVerticalGroup(
            btnElementalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElemental, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(btnElemental, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        lblUltimate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUltimate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUltimateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUltimateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUltimateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnUltimateLayout = new javax.swing.GroupLayout(btnUltimate);
        btnUltimate.setLayout(btnUltimateLayout);
        btnUltimateLayout.setHorizontalGroup(
            btnUltimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUltimate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnUltimateLayout.setVerticalGroup(
            btnUltimateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUltimate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(btnUltimate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 100, 100));
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 430, 80));
        jPanel1.add(lblSubtittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblAnemoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseClicked
        value="A";
        lblSubtittle.setText("<html>Elemento anemo seleccionado<html>");

    }//GEN-LAST:event_lblAnemoMouseClicked

    private void lblAnemoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseEntered
        btnAnemo.setOpaque(true);
        btnAnemo.setBackground(colorEntered);
    }//GEN-LAST:event_lblAnemoMouseEntered

    private void lblAnemoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseExited
        btnAnemo.setOpaque(true);
        btnAnemo.setBackground(colorDefault);
    }//GEN-LAST:event_lblAnemoMouseExited

    private void lblElectroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseClicked
        value="E";
        lblSubtittle.setText("<html>Elemento electro seleccionado<html>");


    }//GEN-LAST:event_lblElectroMouseClicked

    private void lblElectroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseEntered
     
            btnElectro.setOpaque(true);
            btnElectro.setBackground(colorEntered);
        
    }//GEN-LAST:event_lblElectroMouseEntered

    private void lblElectroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseExited
      
            btnElectro.setOpaque(true);
            btnElectro.setBackground(colorDefault);
        
    }//GEN-LAST:event_lblElectroMouseExited

    private void lblDendroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseClicked
        value="D";
        lblSubtittle.setText("<html>Elemento dendro seleccionado<html>");

        
    }//GEN-LAST:event_lblDendroMouseClicked

    private void lblDendroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseEntered

            btnDendro.setOpaque(true);
            btnDendro.setBackground(colorEntered);
    
    }//GEN-LAST:event_lblDendroMouseEntered

    private void lblDendroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseExited

            btnDendro.setOpaque(true);
            btnDendro.setBackground(colorDefault);
       
    }//GEN-LAST:event_lblDendroMouseExited

    private void lblHydroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseClicked
        value="H";
        lblSubtittle.setText("<html>Elemento hydro seleccionado<html>");

    }//GEN-LAST:event_lblHydroMouseClicked

    private void lblHydroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseEntered
        btnHydro.setOpaque(true);
        btnHydro.setBackground(colorEntered);
    }//GEN-LAST:event_lblHydroMouseEntered

    private void lblHydroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseExited
        btnHydro.setOpaque(true);
        btnHydro.setBackground(colorDefault);
    }//GEN-LAST:event_lblHydroMouseExited

    private void lblGeoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseClicked
        value="G";
        lblSubtittle.setText("<html>Elemento geo seleccionado<html>");
    }//GEN-LAST:event_lblGeoMouseClicked

    private void lblGeoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseEntered
        btnGeo.setOpaque(true);
        btnGeo.setBackground(colorEntered);
    }//GEN-LAST:event_lblGeoMouseEntered

    private void lblGeoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseExited
        btnGeo.setOpaque(true);
        btnGeo.setBackground(colorDefault);
    }//GEN-LAST:event_lblGeoMouseExited

    private void lblElementalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElementalMouseEntered
        btnElemental.setOpaque(true);
        btnElemental.setBackground(colorEntered);
    }//GEN-LAST:event_lblElementalMouseEntered

    private void lblElementalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElementalMouseExited
        btnElemental.setOpaque(true);
        btnElemental.setBackground(colorDefault);
    }//GEN-LAST:event_lblElementalMouseExited

    private void lblUltimateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUltimateMouseEntered
        btnUltimate.setOpaque(true);
        btnUltimate.setBackground(colorEntered);
    }//GEN-LAST:event_lblUltimateMouseEntered

    private void lblUltimateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUltimateMouseExited
        btnUltimate.setOpaque(true);
        btnUltimate.setBackground(colorDefault);
    }//GEN-LAST:event_lblUltimateMouseExited

    private void lblElementalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElementalMouseClicked
        if(!this.value.equals("")){
            setImageLabel(lblPj, "src\\Assets\\IMG\\Strategy\\abilities\\elemental"+value+"_Img.jpeg");
            setTxt("elemental");
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar un elemento primero!");
        }
    }//GEN-LAST:event_lblElementalMouseClicked

    private void lblUltimateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUltimateMouseClicked
        if(!this.value.equals("")){
            setImageLabel(lblPj, "src\\Assets\\IMG\\Strategy\\abilities\\ultimate"+value+"_Img.jpeg");
            setTxt("ultimate");
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar un elemento primero!");
        }
    }//GEN-LAST:event_lblUltimateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Strategy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Strategy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnAnemo;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnDendro;
    private javax.swing.JPanel btnElectro;
    private javax.swing.JPanel btnElemental;
    private javax.swing.JPanel btnGeo;
    private javax.swing.JPanel btnHydro;
    private javax.swing.JPanel btnUltimate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnemo;
    private javax.swing.JLabel lblDendro;
    private javax.swing.JLabel lblElectro;
    private javax.swing.JLabel lblElemental;
    private javax.swing.JLabel lblGeo;
    private javax.swing.JLabel lblHydro;
    private javax.swing.JLabel lblPj;
    private javax.swing.JLabel lblSubtittle;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblUltimate;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
