/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Assets.FONT.Fonts;
import java.awt.Image;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Visitor extends javax.swing.JFrame {

    int mouseX, mouseY;
    Fonts typeFont;
    Color colorEntered=new Color(128, 128, 128);
    Color colorDefault=new Color(214, 217, 223);
    int turn=1;
    String element1="", element2="";
    
    public Visitor() {
        initComponents();
        decorator();

    }

    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    private void decorator(){
        typeFont = new Fonts();
        lblText.setFont(typeFont.fontV(typeFont.instruments, 1, 18));
        
        setImageLabel(lblAnemo,"src\\Assets\\IMG\\Visitor\\anemo_Icon.png");
        setImageLabel(lblGeo,"src\\Assets\\IMG\\Visitor\\geo_Icon.png");
        setImageLabel(lblCryo,"src\\Assets\\IMG\\Visitor\\cryo_Icon.png");
        setImageLabel(lblDendro,"src\\Assets\\IMG\\Visitor\\dendro_Icon.png");
        setImageLabel(lblElectro,"src\\Assets\\IMG\\Visitor\\electro_Icon.png");
        setImageLabel(lblHydro,"src\\Assets\\IMG\\Visitor\\hydro_Icon.png");
        setImageLabel(lblPyro,"src\\Assets\\IMG\\Visitor\\pyro_Icon.png");
        setImageLabel(lblEnemy,"src\\Assets\\IMG\\Visitor\\enemy_Img.png");
        setImageLabel(lblCombination,"src\\Assets\\IMG\\Visitor\\combination_Img.png");
        


    }
    
    private String validateElement(String element1, String element2){

        
        Map<Set<String>, String> reacciones = new HashMap<>();
        reacciones.put(new HashSet<>(Arrays.asList("pyro", "hydro")), "Vaporizar");
        reacciones.put(new HashSet<>(Arrays.asList("pyro", "cryo")), "Derretir");
        reacciones.put(new HashSet<>(Arrays.asList("hydro", "cryo")), "Congelación");
        reacciones.put(new HashSet<>(Arrays.asList("electro", "pyro")), "Sobrecarga");
        reacciones.put(new HashSet<>(Arrays.asList("electro", "hydro")), "Electrocargado");
        reacciones.put(new HashSet<>(Arrays.asList("electro", "cryo")), "Superconductor");
        reacciones.put(new HashSet<>(Arrays.asList("anemo", "pyro")), "Torbellino (Pyro)");
        reacciones.put(new HashSet<>(Arrays.asList("anemo", "hydro")), "Torbellino (Hydro)");
        reacciones.put(new HashSet<>(Arrays.asList("anemo", "cryo")), "Torbellino (Cryo)");
        reacciones.put(new HashSet<>(Arrays.asList("anemo", "electro")), "Torbellino (Electro)");
        reacciones.put(new HashSet<>(Arrays.asList("geo", "pyro")), "Cristalización (Pyro)");
        reacciones.put(new HashSet<>(Arrays.asList("geo", "hydro")), "Cristalización (Hydro)");
        reacciones.put(new HashSet<>(Arrays.asList("geo", "cryo")), "Cristalización (Cryo)");
        reacciones.put(new HashSet<>(Arrays.asList("geo", "electro")), "Cristalización (Electro)");
        reacciones.put(new HashSet<>(Arrays.asList("dendro", "electro")), "Intensificado");
        reacciones.put(new HashSet<>(Arrays.asList("dendro", "hydro")), "Bloom");
        reacciones.put(new HashSet<>(Arrays.asList("dendro", "pyro")), "Quemadura");

        
        Set<String> conjuntoElementos = new HashSet<>(Arrays.asList(element1, element2));

        
       return reacciones.getOrDefault(conjuntoElementos, "No hay reacción elemental válida o combinación desconocida.");
        
        
    }
    
    private void setElement(String element){
        
        if((turn%2)!=0){
           setImageLabel(lblElement1,"src\\Assets\\IMG\\Visitor\\"+element+"_Icon.png"); 
           this.element1=element;
        
        }else if((turn%2)==0){
           lblPluse.setText("+");
           setImageLabel(lblElement2,"src\\Assets\\IMG\\Visitor\\"+element+"_Icon.png"); 
           this.element2=element;

            lblText.setText("<html>"+validateElement(this.element1, this.element2)+"<html>");
           
           
        }
        turn++;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        txtCerrar = new javax.swing.JLabel();
        pnlSeparator = new javax.swing.JPanel();
        btnAnemo = new javax.swing.JPanel();
        lblAnemo = new javax.swing.JLabel();
        btnElectro = new javax.swing.JPanel();
        lblElectro = new javax.swing.JLabel();
        btnDendro = new javax.swing.JPanel();
        lblDendro = new javax.swing.JLabel();
        btnHydro = new javax.swing.JPanel();
        lblHydro = new javax.swing.JLabel();
        btnGeo = new javax.swing.JPanel();
        lblGeo = new javax.swing.JLabel();
        btnPyro = new javax.swing.JPanel();
        lblPyro = new javax.swing.JLabel();
        btnCryo = new javax.swing.JPanel();
        lblCryo = new javax.swing.JLabel();
        lblEnemy = new javax.swing.JLabel();
        lblPluse = new javax.swing.JLabel();
        lblElement2 = new javax.swing.JLabel();
        lblElement1 = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        pnlSeparator3 = new javax.swing.JPanel();
        pnlSeparator2 = new javax.swing.JPanel();
        lblCombination = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        btnClose.setBackground(new java.awt.Color(217, 152, 141));
        btnClose.setToolTipText("");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);

        txtCerrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrar.setText("X");
        txtCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtCerrar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 60));

        pnlSeparator.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparatorLayout = new javax.swing.GroupLayout(pnlSeparator);
        pnlSeparator.setLayout(pnlSeparatorLayout);
        pnlSeparatorLayout.setHorizontalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSeparatorLayout.setVerticalGroup(
            pnlSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 3));

        btnAnemo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAnemo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnemoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAnemoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAnemoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAnemoLayout = new javax.swing.GroupLayout(btnAnemo);
        btnAnemo.setLayout(btnAnemoLayout);
        btnAnemoLayout.setHorizontalGroup(
            btnAnemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnemo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnAnemoLayout.setVerticalGroup(
            btnAnemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnemo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnAnemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 50, 50));

        btnElectro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblElectro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblElectroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblElectroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblElectroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnElectroLayout = new javax.swing.GroupLayout(btnElectro);
        btnElectro.setLayout(btnElectroLayout);
        btnElectroLayout.setHorizontalGroup(
            btnElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElectro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnElectroLayout.setVerticalGroup(
            btnElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblElectro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnElectro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 50, 50));

        btnDendro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDendro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDendroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDendroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDendroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDendroLayout = new javax.swing.GroupLayout(btnDendro);
        btnDendro.setLayout(btnDendroLayout);
        btnDendroLayout.setHorizontalGroup(
            btnDendroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDendro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnDendroLayout.setVerticalGroup(
            btnDendroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDendro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnDendro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 50));

        btnHydro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblHydro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHydroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHydroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHydroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHydroLayout = new javax.swing.GroupLayout(btnHydro);
        btnHydro.setLayout(btnHydroLayout);
        btnHydroLayout.setHorizontalGroup(
            btnHydroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHydro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnHydroLayout.setVerticalGroup(
            btnHydroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHydro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnHydro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        btnGeo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGeoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGeoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGeoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGeoLayout = new javax.swing.GroupLayout(btnGeo);
        btnGeo.setLayout(btnGeoLayout);
        btnGeoLayout.setHorizontalGroup(
            btnGeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGeo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnGeoLayout.setVerticalGroup(
            btnGeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGeo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, 50));

        btnPyro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPyro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPyroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPyroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPyroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPyroLayout = new javax.swing.GroupLayout(btnPyro);
        btnPyro.setLayout(btnPyroLayout);
        btnPyroLayout.setHorizontalGroup(
            btnPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPyro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnPyroLayout.setVerticalGroup(
            btnPyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPyro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnPyro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));

        btnCryo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCryo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCryoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCryoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCryoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCryoLayout = new javax.swing.GroupLayout(btnCryo);
        btnCryo.setLayout(btnCryoLayout);
        btnCryoLayout.setHorizontalGroup(
            btnCryoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCryo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        btnCryoLayout.setVerticalGroup(
            btnCryoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCryo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCryo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 50, 50));

        lblEnemy.setText("jLabel1");
        jPanel1.add(lblEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 250, 280));

        lblPluse.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPluse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPluse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblPluse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 50, 50));
        jPanel1.add(lblElement2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 50, 50));
        jPanel1.add(lblElement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 50, 50));
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 270, 90));

        pnlSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator3Layout = new javax.swing.GroupLayout(pnlSeparator3);
        pnlSeparator3.setLayout(pnlSeparator3Layout);
        pnlSeparator3Layout.setHorizontalGroup(
            pnlSeparator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlSeparator3Layout.setVerticalGroup(
            pnlSeparator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 300, 2));

        pnlSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlSeparator2Layout = new javax.swing.GroupLayout(pnlSeparator2);
        pnlSeparator2.setLayout(pnlSeparator2Layout);
        pnlSeparator2Layout.setHorizontalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        pnlSeparator2Layout.setVerticalGroup(
            pnlSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(pnlSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 2, 240));

        lblCombination.setText("jLabel1");
        jPanel1.add(lblCombination, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 280, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        mouseX=evt.getX();
        mouseY=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void txtCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtCerrarMouseClicked

    private void txtCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseEntered
        btnClose.setOpaque(true);
        btnClose.setBackground(Color.red);
    }//GEN-LAST:event_txtCerrarMouseEntered

    private void txtCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarMouseExited
        btnClose.setBackground(Color.pink);
        btnClose.setOpaque(false);
    }//GEN-LAST:event_txtCerrarMouseExited

    private void lblAnemoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseClicked
        setElement("anemo");
    }//GEN-LAST:event_lblAnemoMouseClicked

    private void lblAnemoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseEntered
        btnAnemo.setOpaque(true);
        btnAnemo.setBackground(colorEntered);
    }//GEN-LAST:event_lblAnemoMouseEntered

    private void lblAnemoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnemoMouseExited
        btnAnemo.setOpaque(true);
        btnAnemo.setBackground(colorDefault);
    }//GEN-LAST:event_lblAnemoMouseExited

    private void lblElectroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseClicked
        setElement("electro");

    }//GEN-LAST:event_lblElectroMouseClicked

    private void lblElectroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseEntered

        btnElectro.setOpaque(true);
        btnElectro.setBackground(colorEntered);

    }//GEN-LAST:event_lblElectroMouseEntered

    private void lblElectroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblElectroMouseExited

        btnElectro.setOpaque(true);
        btnElectro.setBackground(colorDefault);

    }//GEN-LAST:event_lblElectroMouseExited

    private void lblDendroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseClicked
        setElement("dendro");

    }//GEN-LAST:event_lblDendroMouseClicked

    private void lblDendroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseEntered

        btnDendro.setOpaque(true);
        btnDendro.setBackground(colorEntered);

    }//GEN-LAST:event_lblDendroMouseEntered

    private void lblDendroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDendroMouseExited

        btnDendro.setOpaque(true);
        btnDendro.setBackground(colorDefault);

    }//GEN-LAST:event_lblDendroMouseExited

    private void lblHydroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseClicked
        setElement("hydro");
    }//GEN-LAST:event_lblHydroMouseClicked

    private void lblHydroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseEntered
        btnHydro.setOpaque(true);
        btnHydro.setBackground(colorEntered);
    }//GEN-LAST:event_lblHydroMouseEntered

    private void lblHydroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHydroMouseExited
        btnHydro.setOpaque(true);
        btnHydro.setBackground(colorDefault);
    }//GEN-LAST:event_lblHydroMouseExited

    private void lblGeoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseClicked
        setElement("geo");
    }//GEN-LAST:event_lblGeoMouseClicked

    private void lblGeoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseEntered
        btnGeo.setOpaque(true);
        btnGeo.setBackground(colorEntered);
    }//GEN-LAST:event_lblGeoMouseEntered

    private void lblGeoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGeoMouseExited
        btnGeo.setOpaque(true);
        btnGeo.setBackground(colorDefault);
    }//GEN-LAST:event_lblGeoMouseExited

    private void lblPyroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPyroMouseClicked
       setElement("pyro");
    }//GEN-LAST:event_lblPyroMouseClicked

    private void lblPyroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPyroMouseEntered
        btnPyro.setOpaque(true);
        btnPyro.setBackground(colorEntered);
    }//GEN-LAST:event_lblPyroMouseEntered

    private void lblPyroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPyroMouseExited
        btnPyro.setOpaque(true);
        btnPyro.setBackground(colorDefault);
    }//GEN-LAST:event_lblPyroMouseExited

    private void lblCryoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCryoMouseClicked
       setElement("cryo");
    }//GEN-LAST:event_lblCryoMouseClicked

    private void lblCryoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCryoMouseEntered
        btnCryo.setOpaque(true);
        btnCryo.setBackground(colorEntered);
    }//GEN-LAST:event_lblCryoMouseEntered

    private void lblCryoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCryoMouseExited
        btnCryo.setOpaque(true);
        btnCryo.setBackground(colorDefault);
    }//GEN-LAST:event_lblCryoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnAnemo;
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnCryo;
    private javax.swing.JPanel btnDendro;
    private javax.swing.JPanel btnElectro;
    private javax.swing.JPanel btnGeo;
    private javax.swing.JPanel btnHydro;
    private javax.swing.JPanel btnPyro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnemo;
    private javax.swing.JLabel lblCombination;
    private javax.swing.JLabel lblCryo;
    private javax.swing.JLabel lblDendro;
    private javax.swing.JLabel lblElectro;
    private javax.swing.JLabel lblElement1;
    private javax.swing.JLabel lblElement2;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblGeo;
    private javax.swing.JLabel lblHydro;
    private javax.swing.JLabel lblPluse;
    private javax.swing.JLabel lblPyro;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel pnlSeparator;
    private javax.swing.JPanel pnlSeparator2;
    private javax.swing.JPanel pnlSeparator3;
    private javax.swing.JLabel txtCerrar;
    // End of variables declaration//GEN-END:variables
}
